// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "matrix_mul_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic matrix_mul_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic matrix_mul_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<11> matrix_mul_1::ap_ST_fsm_state1 = "1";
const sc_lv<11> matrix_mul_1::ap_ST_fsm_state2 = "10";
const sc_lv<11> matrix_mul_1::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<11> matrix_mul_1::ap_ST_fsm_state5 = "1000";
const sc_lv<11> matrix_mul_1::ap_ST_fsm_state6 = "10000";
const sc_lv<11> matrix_mul_1::ap_ST_fsm_state7 = "100000";
const sc_lv<11> matrix_mul_1::ap_ST_fsm_state8 = "1000000";
const sc_lv<11> matrix_mul_1::ap_ST_fsm_state9 = "10000000";
const sc_lv<11> matrix_mul_1::ap_ST_fsm_state10 = "100000000";
const sc_lv<11> matrix_mul_1::ap_ST_fsm_pp1_stage0 = "1000000000";
const sc_lv<11> matrix_mul_1::ap_ST_fsm_state13 = "10000000000";
const bool matrix_mul_1::ap_const_boolean_1 = true;
const sc_lv<32> matrix_mul_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> matrix_mul_1::ap_const_lv32_1 = "1";
const sc_lv<1> matrix_mul_1::ap_const_lv1_0 = "0";
const sc_lv<32> matrix_mul_1::ap_const_lv32_2 = "10";
const bool matrix_mul_1::ap_const_boolean_0 = false;
const sc_lv<32> matrix_mul_1::ap_const_lv32_4 = "100";
const sc_lv<32> matrix_mul_1::ap_const_lv32_5 = "101";
const sc_lv<1> matrix_mul_1::ap_const_lv1_1 = "1";
const sc_lv<32> matrix_mul_1::ap_const_lv32_6 = "110";
const sc_lv<32> matrix_mul_1::ap_const_lv32_7 = "111";
const sc_lv<32> matrix_mul_1::ap_const_lv32_9 = "1001";
const sc_lv<8> matrix_mul_1::ap_const_lv8_0 = "00000000";
const sc_lv<32> matrix_mul_1::ap_const_lv32_8 = "1000";
const sc_lv<3> matrix_mul_1::ap_const_lv3_0 = "000";
const sc_lv<3> matrix_mul_1::ap_const_lv3_1 = "1";
const sc_lv<64> matrix_mul_1::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> matrix_mul_1::ap_const_lv32_3 = "11";
const sc_lv<4> matrix_mul_1::ap_const_lv4_0 = "0000";
const sc_lv<8> matrix_mul_1::ap_const_lv8_80 = "10000000";
const sc_lv<8> matrix_mul_1::ap_const_lv8_1 = "1";
const sc_lv<2> matrix_mul_1::ap_const_lv2_0 = "00";
const sc_lv<3> matrix_mul_1::ap_const_lv3_4 = "100";
const sc_lv<2> matrix_mul_1::ap_const_lv2_1 = "1";
const sc_lv<3> matrix_mul_1::ap_const_lv3_2 = "10";
const sc_lv<32> matrix_mul_1::ap_const_lv32_1F = "11111";
const sc_lv<32> matrix_mul_1::ap_const_lv32_18 = "11000";
const sc_lv<32> matrix_mul_1::ap_const_lv32_19 = "11001";
const sc_lv<32> matrix_mul_1::ap_const_lv32_1B = "11011";
const sc_lv<32> matrix_mul_1::ap_const_lv32_10 = "10000";
const sc_lv<6> matrix_mul_1::ap_const_lv6_7 = "111";
const sc_lv<6> matrix_mul_1::ap_const_lv6_1F = "11111";
const sc_lv<32> matrix_mul_1::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<3> matrix_mul_1::ap_const_lv3_7 = "111";
const sc_lv<8> matrix_mul_1::ap_const_lv8_FF = "11111111";
const sc_lv<4> matrix_mul_1::ap_const_lv4_1 = "1";
const sc_lv<32> matrix_mul_1::ap_const_lv32_A = "1010";

matrix_mul_1::matrix_mul_1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    temp_matrix_U = new matrix_mul_1_tempeOg("temp_matrix_U");
    temp_matrix_U->clk(ap_clk);
    temp_matrix_U->reset(ap_rst);
    temp_matrix_U->address0(temp_matrix_address0);
    temp_matrix_U->ce0(temp_matrix_ce0);
    temp_matrix_U->q0(temp_matrix_q0);
    temp_matrix_U->address1(temp_matrix_address1);
    temp_matrix_U->ce1(temp_matrix_ce1);
    temp_matrix_U->q1(temp_matrix_q1);
    prod_U = new matrix_mul_1_prod("prod_U");
    prod_U->clk(ap_clk);
    prod_U->reset(ap_rst);
    prod_U->address0(prod_address0);
    prod_U->ce0(prod_ce0);
    prod_U->we0(prod_we0);
    prod_U->d0(prod_d0);
    prod_U->q0(prod_q0);
    prod_U->address1(prod_address1);
    prod_U->ce1(prod_ce1);
    prod_U->we1(prod_we1);
    prod_U->d1(prod_d1);
    prod_U->q1(prod_q1);
    temp_U = new matrix_mul_1_temp("temp_U");
    temp_U->clk(ap_clk);
    temp_U->reset(ap_rst);
    temp_U->address0(temp_address0);
    temp_U->ce0(temp_ce0);
    temp_U->we0(temp_we0);
    temp_U->d0(temp_d0);
    temp_U->q0(temp_q0);
    temp_U->address1(temp_address1);
    temp_U->ce1(temp_ce1);
    temp_U->q1(temp_q1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln130_fu_430_p2);
    sensitive << ( j_0_0_reg_289 );

    SC_METHOD(thread_add_ln133_1_fu_404_p3);
    sensitive << ( trunc_ln133_reg_1036 );
    sensitive << ( or_ln130_fu_398_p2 );

    SC_METHOD(thread_add_ln133_fu_374_p2);
    sensitive << ( shl_ln_reg_1041 );
    sensitive << ( zext_ln130_fu_370_p1 );

    SC_METHOD(thread_add_ln134_1_fu_420_p2);
    sensitive << ( matrix_offset );
    sensitive << ( zext_ln134_4_fu_411_p1 );

    SC_METHOD(thread_add_ln134_fu_388_p2);
    sensitive << ( matrix_offset );
    sensitive << ( zext_ln134_2_fu_379_p1 );

    SC_METHOD(thread_add_ln139_fu_1005_p2);
    sensitive << ( loop_0_0_reg_321 );

    SC_METHOD(thread_add_ln68_fu_719_p2);
    sensitive << ( zext_ln68_fu_711_p1 );

    SC_METHOD(thread_and_ln68_1_fu_817_p2);
    sensitive << ( lshr_ln68_fu_805_p2 );
    sensitive << ( lshr_ln68_1_fu_811_p2 );

    SC_METHOD(thread_and_ln68_2_fu_956_p2);
    sensitive << ( shl_ln68_3_fu_944_p2 );
    sensitive << ( lshr_ln68_2_fu_950_p2 );

    SC_METHOD(thread_and_ln68_fu_854_p2);
    sensitive << ( trunc_ln68_fu_823_p1 );
    sensitive << ( xor_ln68_1_fu_842_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp1_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_pp1_stage0);

    SC_METHOD(thread_ap_block_pp1_stage0_11001);

    SC_METHOD(thread_ap_block_pp1_stage0_subdone);

    SC_METHOD(thread_ap_block_state11_pp1_stage0_iter0);

    SC_METHOD(thread_ap_block_state12_pp1_stage0_iter1);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( icmp_ln130_fu_360_p2 );

    SC_METHOD(thread_ap_condition_pp1_exit_iter0_state11);
    sensitive << ( icmp_ln139_fu_979_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_pp1);
    sensitive << ( ap_idle_pp1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_idle_pp1);
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_i_1_fu_461_p2);
    sensitive << ( i_0_i_reg_310 );

    SC_METHOD(thread_i_fu_338_p2);
    sensitive << ( bitNumber_assign_reg_277 );

    SC_METHOD(thread_icmp_ln129_fu_332_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( bitNumber_assign_reg_277 );

    SC_METHOD(thread_icmp_ln130_fu_360_p2);
    sensitive << ( j_0_0_reg_289 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln139_fu_979_p2);
    sensitive << ( loop_0_0_reg_321 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_icmp_ln68_1_fu_866_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( zext_ln68_2_fu_715_p1 );
    sensitive << ( zext_ln68_4_fu_725_p1 );

    SC_METHOD(thread_icmp_ln68_fu_729_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( zext_ln68_2_fu_715_p1 );
    sensitive << ( zext_ln68_4_fu_725_p1 );

    SC_METHOD(thread_icmp_ln87_fu_455_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( i_0_i_reg_310 );

    SC_METHOD(thread_lshr_ln1_fu_544_p4);
    sensitive << ( y_fu_538_p2 );

    SC_METHOD(thread_lshr_ln2_fu_588_p4);
    sensitive << ( y_1_fu_582_p2 );

    SC_METHOD(thread_lshr_ln68_1_fu_811_p2);
    sensitive << ( zext_ln68_7_fu_801_p1 );

    SC_METHOD(thread_lshr_ln68_2_fu_950_p2);
    sensitive << ( zext_ln68_12_fu_917_p1 );

    SC_METHOD(thread_lshr_ln68_fu_805_p2);
    sensitive << ( select_ln68_1_fu_775_p3 );
    sensitive << ( zext_ln68_6_fu_797_p1 );

    SC_METHOD(thread_lshr_ln_fu_498_p4);
    sensitive << ( x_0_i_reg_300 );

    SC_METHOD(thread_or_ln130_fu_398_p2);
    sensitive << ( trunc_ln130_fu_366_p1 );

    SC_METHOD(thread_or_ln139_fu_994_p2);
    sensitive << ( trunc_ln139_fu_985_p1 );

    SC_METHOD(thread_or_ln68_fu_860_p2);
    sensitive << ( and_ln68_fu_854_p2 );
    sensitive << ( shl_ln68_1_fu_848_p2 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( zext_ln142_reg_1147 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_output_r_address1);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( zext_ln142_1_reg_1157 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_output_r_ce1);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( temp_q0 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_output_r_d1);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_enable_reg_pp1_iter1 );
    sensitive << ( temp_q1 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( icmp_ln139_reg_1143 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_output_r_we1);
    sensitive << ( icmp_ln139_reg_1143 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter1 );

    SC_METHOD(thread_prod_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( zext_ln134_reg_1050 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_prod_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( zext_ln134_1_reg_1065 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln87_fu_450_p1 );

    SC_METHOD(thread_prod_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_prod_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_prod_d0);
    sensitive << ( state_q0 );
    sensitive << ( temp_matrix_q0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_prod_d1);
    sensitive << ( state_q1 );
    sensitive << ( temp_matrix_q1 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_prod_we0);
    sensitive << ( icmp_ln130_reg_1046 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_prod_we1);
    sensitive << ( icmp_ln130_reg_1046 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_select_ln68_1_fu_775_p3);
    sensitive << ( temp_q0 );
    sensitive << ( icmp_ln68_fu_729_p2 );
    sensitive << ( tmp_10_fu_739_p4 );

    SC_METHOD(thread_select_ln68_2_fu_783_p3);
    sensitive << ( zext_ln68_5_fu_735_p1 );
    sensitive << ( icmp_ln68_fu_729_p2 );
    sensitive << ( xor_ln68_2_fu_755_p2 );

    SC_METHOD(thread_select_ln68_3_fu_884_p3);
    sensitive << ( add_ln68_reg_1124 );
    sensitive << ( icmp_ln68_1_reg_1135 );
    sensitive << ( zext_ln68_8_fu_872_p1 );

    SC_METHOD(thread_select_ln68_4_fu_890_p3);
    sensitive << ( add_ln68_reg_1124 );
    sensitive << ( icmp_ln68_1_reg_1135 );
    sensitive << ( zext_ln68_8_fu_872_p1 );

    SC_METHOD(thread_select_ln68_5_fu_896_p3);
    sensitive << ( icmp_ln68_1_reg_1135 );
    sensitive << ( zext_ln68_8_fu_872_p1 );
    sensitive << ( xor_ln68_3_fu_878_p2 );

    SC_METHOD(thread_select_ln68_6_fu_937_p3);
    sensitive << ( icmp_ln68_1_reg_1135 );
    sensitive << ( shl_ln68_2_fu_921_p2 );
    sensitive << ( tmp_11_fu_927_p4 );

    SC_METHOD(thread_select_ln68_fu_767_p3);
    sensitive << ( icmp_ln68_fu_729_p2 );
    sensitive << ( sub_ln68_fu_749_p2 );
    sensitive << ( sub_ln68_1_fu_761_p2 );

    SC_METHOD(thread_shl_ln68_1_fu_848_p2);
    sensitive << ( zext_ln68_1_fu_832_p1 );
    sensitive << ( zext_ln100_fu_700_p1 );

    SC_METHOD(thread_shl_ln68_2_fu_921_p2);
    sensitive << ( zext_ln68_9_fu_875_p1 );
    sensitive << ( zext_ln68_10_fu_909_p1 );

    SC_METHOD(thread_shl_ln68_3_fu_944_p2);
    sensitive << ( zext_ln68_11_fu_913_p1 );

    SC_METHOD(thread_shl_ln68_4_fu_972_p2);
    sensitive << ( zext_ln68_13_fu_969_p1 );

    SC_METHOD(thread_shl_ln68_fu_836_p2);
    sensitive << ( zext_ln68_1_fu_832_p1 );

    SC_METHOD(thread_shl_ln_fu_352_p3);
    sensitive << ( trunc_ln133_fu_348_p1 );

    SC_METHOD(thread_state_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( zext_ln134_fu_383_p1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_state_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( zext_ln134_1_fu_415_p1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_state_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_state_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_sub_ln68_1_fu_761_p2);
    sensitive << ( add_ln68_fu_719_p2 );
    sensitive << ( zext_ln68_5_fu_735_p1 );

    SC_METHOD(thread_sub_ln68_2_fu_791_p2);
    sensitive << ( select_ln68_fu_767_p3 );

    SC_METHOD(thread_sub_ln68_3_fu_903_p2);
    sensitive << ( select_ln68_3_fu_884_p3 );

    SC_METHOD(thread_sub_ln68_fu_749_p2);
    sensitive << ( add_ln68_fu_719_p2 );
    sensitive << ( zext_ln68_5_fu_735_p1 );

    SC_METHOD(thread_temp_address0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( temp_addr_9_reg_1109 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( zext_ln142_fu_989_p1 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( zext_ln68_3_fu_487_p1 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_temp_address1);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( zext_ln142_1_fu_1000_p1 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_block_pp1_stage0 );

    SC_METHOD(thread_temp_ce0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_temp_ce1);
    sensitive << ( ap_CS_fsm_pp1_stage0 );
    sensitive << ( ap_block_pp1_stage0_11001 );
    sensitive << ( ap_enable_reg_pp1_iter0 );

    SC_METHOD(thread_temp_d0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( select_ln68_6_fu_937_p3 );
    sensitive << ( and_ln68_2_fu_956_p2 );

    SC_METHOD(thread_temp_matrix_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln134_3_fu_393_p1 );

    SC_METHOD(thread_temp_matrix_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln134_5_fu_425_p1 );

    SC_METHOD(thread_temp_matrix_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_temp_matrix_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_temp_we0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( shl_ln68_4_fu_972_p2 );

    SC_METHOD(thread_tmp_10_fu_739_p4);
    sensitive << ( temp_q0 );

    SC_METHOD(thread_tmp_11_fu_927_p4);
    sensitive << ( shl_ln68_2_fu_921_p2 );

    SC_METHOD(thread_tmp_1_fu_516_p3);
    sensitive << ( x_0_i_reg_300 );

    SC_METHOD(thread_tmp_4_fu_558_p3);
    sensitive << ( y_fu_538_p2 );

    SC_METHOD(thread_tmp_5_fu_602_p3);
    sensitive << ( y_1_fu_582_p2 );

    SC_METHOD(thread_tmp_6_fu_648_p3);
    sensitive << ( y_2_fu_626_p2 );

    SC_METHOD(thread_tmp_7_fu_662_p3);
    sensitive << ( y_3_fu_656_p2 );

    SC_METHOD(thread_tmp_9_fu_477_p4);
    sensitive << ( bitNumber_assign_reg_277 );

    SC_METHOD(thread_trunc_ln129_fu_344_p1);
    sensitive << ( bitNumber_assign_reg_277 );

    SC_METHOD(thread_trunc_ln130_fu_366_p1);
    sensitive << ( j_0_0_reg_289 );

    SC_METHOD(thread_trunc_ln133_fu_348_p1);
    sensitive << ( bitNumber_assign_reg_277 );

    SC_METHOD(thread_trunc_ln139_fu_985_p1);
    sensitive << ( loop_0_0_reg_321 );

    SC_METHOD(thread_trunc_ln68_fu_823_p1);
    sensitive << ( and_ln68_1_fu_817_p2 );

    SC_METHOD(thread_trunc_ln6_fu_638_p4);
    sensitive << ( y_2_fu_626_p2 );

    SC_METHOD(thread_trunc_ln95_1_fu_524_p1);
    sensitive << ( x_0_i_reg_300 );

    SC_METHOD(thread_trunc_ln95_3_fu_528_p4);
    sensitive << ( x_0_i_reg_300 );

    SC_METHOD(thread_trunc_ln95_fu_512_p1);
    sensitive << ( x_0_i_reg_300 );

    SC_METHOD(thread_trunc_ln96_1_fu_572_p4);
    sensitive << ( y_fu_538_p2 );

    SC_METHOD(thread_trunc_ln97_1_fu_616_p4);
    sensitive << ( y_1_fu_582_p2 );

    SC_METHOD(thread_x_1_fu_492_p2);
    sensitive << ( prod_q1 );
    sensitive << ( x_0_i_reg_300 );

    SC_METHOD(thread_xor_ln100_1_fu_676_p2);
    sensitive << ( xor_ln100_fu_670_p2 );
    sensitive << ( tmp_1_fu_516_p3 );

    SC_METHOD(thread_xor_ln100_2_fu_682_p2);
    sensitive << ( tmp_6_fu_648_p3 );
    sensitive << ( tmp_7_fu_662_p3 );

    SC_METHOD(thread_xor_ln100_3_fu_688_p2);
    sensitive << ( xor_ln100_2_fu_682_p2 );
    sensitive << ( tmp_5_fu_602_p3 );

    SC_METHOD(thread_xor_ln100_4_fu_694_p2);
    sensitive << ( xor_ln100_3_fu_688_p2 );
    sensitive << ( xor_ln100_1_fu_676_p2 );

    SC_METHOD(thread_xor_ln100_fu_670_p2);
    sensitive << ( trunc_ln95_fu_512_p1 );
    sensitive << ( tmp_4_fu_558_p3 );

    SC_METHOD(thread_xor_ln68_1_fu_842_p2);
    sensitive << ( shl_ln68_fu_836_p2 );

    SC_METHOD(thread_xor_ln68_2_fu_755_p2);
    sensitive << ( zext_ln68_5_fu_735_p1 );

    SC_METHOD(thread_xor_ln68_3_fu_878_p2);
    sensitive << ( zext_ln68_8_fu_872_p1 );

    SC_METHOD(thread_xor_ln68_fu_827_p2);
    sensitive << ( trunc_ln129_reg_1031 );

    SC_METHOD(thread_xor_ln96_fu_566_p2);
    sensitive << ( trunc_ln95_3_fu_528_p4 );
    sensitive << ( trunc_ln95_1_fu_524_p1 );

    SC_METHOD(thread_xor_ln97_2_fu_632_p2);
    sensitive << ( trunc_ln97_1_fu_616_p4 );
    sensitive << ( xor_ln97_fu_610_p2 );

    SC_METHOD(thread_xor_ln97_fu_610_p2);
    sensitive << ( trunc_ln96_1_fu_572_p4 );
    sensitive << ( xor_ln96_fu_566_p2 );

    SC_METHOD(thread_y_1_fu_582_p2);
    sensitive << ( y_fu_538_p2 );
    sensitive << ( zext_ln96_fu_554_p1 );

    SC_METHOD(thread_y_2_fu_626_p2);
    sensitive << ( y_1_fu_582_p2 );
    sensitive << ( zext_ln97_fu_598_p1 );

    SC_METHOD(thread_y_3_fu_656_p2);
    sensitive << ( trunc_ln6_fu_638_p4 );
    sensitive << ( xor_ln97_2_fu_632_p2 );

    SC_METHOD(thread_y_fu_538_p2);
    sensitive << ( x_0_i_reg_300 );
    sensitive << ( zext_ln95_fu_508_p1 );

    SC_METHOD(thread_zext_ln100_fu_700_p1);
    sensitive << ( xor_ln100_4_fu_694_p2 );

    SC_METHOD(thread_zext_ln130_fu_370_p1);
    sensitive << ( j_0_0_reg_289 );

    SC_METHOD(thread_zext_ln134_1_fu_415_p1);
    sensitive << ( or_ln130_fu_398_p2 );

    SC_METHOD(thread_zext_ln134_2_fu_379_p1);
    sensitive << ( add_ln133_fu_374_p2 );

    SC_METHOD(thread_zext_ln134_3_fu_393_p1);
    sensitive << ( add_ln134_fu_388_p2 );

    SC_METHOD(thread_zext_ln134_4_fu_411_p1);
    sensitive << ( add_ln133_1_fu_404_p3 );

    SC_METHOD(thread_zext_ln134_5_fu_425_p1);
    sensitive << ( add_ln134_1_fu_420_p2 );

    SC_METHOD(thread_zext_ln134_fu_383_p1);
    sensitive << ( j_0_0_reg_289 );

    SC_METHOD(thread_zext_ln142_1_fu_1000_p1);
    sensitive << ( or_ln139_fu_994_p2 );

    SC_METHOD(thread_zext_ln142_fu_989_p1);
    sensitive << ( loop_0_0_reg_321 );

    SC_METHOD(thread_zext_ln68_10_fu_909_p1);
    sensitive << ( select_ln68_5_fu_896_p3 );

    SC_METHOD(thread_zext_ln68_11_fu_913_p1);
    sensitive << ( select_ln68_4_fu_890_p3 );

    SC_METHOD(thread_zext_ln68_12_fu_917_p1);
    sensitive << ( sub_ln68_3_fu_903_p2 );

    SC_METHOD(thread_zext_ln68_13_fu_969_p1);
    sensitive << ( tmp_8_reg_1103 );

    SC_METHOD(thread_zext_ln68_1_fu_832_p1);
    sensitive << ( xor_ln68_fu_827_p2 );

    SC_METHOD(thread_zext_ln68_2_fu_715_p1);
    sensitive << ( zext_ln68_cast_fu_704_p3 );

    SC_METHOD(thread_zext_ln68_3_fu_487_p1);
    sensitive << ( tmp_9_fu_477_p4 );

    SC_METHOD(thread_zext_ln68_4_fu_725_p1);
    sensitive << ( add_ln68_fu_719_p2 );

    SC_METHOD(thread_zext_ln68_5_fu_735_p1);
    sensitive << ( zext_ln68_cast_fu_704_p3 );

    SC_METHOD(thread_zext_ln68_6_fu_797_p1);
    sensitive << ( select_ln68_2_fu_783_p3 );

    SC_METHOD(thread_zext_ln68_7_fu_801_p1);
    sensitive << ( sub_ln68_2_fu_791_p2 );

    SC_METHOD(thread_zext_ln68_8_fu_872_p1);
    sensitive << ( zext_ln68_cast_reg_1119 );

    SC_METHOD(thread_zext_ln68_9_fu_875_p1);
    sensitive << ( or_ln68_reg_1130 );

    SC_METHOD(thread_zext_ln68_cast_fu_704_p3);
    sensitive << ( tmp_8_reg_1103 );

    SC_METHOD(thread_zext_ln68_fu_711_p1);
    sensitive << ( zext_ln68_cast_fu_704_p3 );

    SC_METHOD(thread_zext_ln87_fu_450_p1);
    sensitive << ( i_0_i_reg_310 );

    SC_METHOD(thread_zext_ln95_fu_508_p1);
    sensitive << ( lshr_ln_fu_498_p4 );

    SC_METHOD(thread_zext_ln96_fu_554_p1);
    sensitive << ( lshr_ln1_fu_544_p4 );

    SC_METHOD(thread_zext_ln97_fu_598_p1);
    sensitive << ( lshr_ln2_fu_588_p4 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln129_fu_332_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln130_fu_360_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln87_fu_455_p2 );
    sensitive << ( icmp_ln139_fu_979_p2 );
    sensitive << ( ap_enable_reg_pp1_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp1_stage0_subdone );

    ap_CS_fsm = "00000000001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp1_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "matrix_mul_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
    sc_trace(mVcdFile, output_r_address1, "(port)output_r_address1");
    sc_trace(mVcdFile, output_r_ce1, "(port)output_r_ce1");
    sc_trace(mVcdFile, output_r_we1, "(port)output_r_we1");
    sc_trace(mVcdFile, output_r_d1, "(port)output_r_d1");
    sc_trace(mVcdFile, state_address0, "(port)state_address0");
    sc_trace(mVcdFile, state_ce0, "(port)state_ce0");
    sc_trace(mVcdFile, state_q0, "(port)state_q0");
    sc_trace(mVcdFile, state_address1, "(port)state_address1");
    sc_trace(mVcdFile, state_ce1, "(port)state_ce1");
    sc_trace(mVcdFile, state_q1, "(port)state_q1");
    sc_trace(mVcdFile, matrix_offset, "(port)matrix_offset");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, temp_matrix_address0, "temp_matrix_address0");
    sc_trace(mVcdFile, temp_matrix_ce0, "temp_matrix_ce0");
    sc_trace(mVcdFile, temp_matrix_q0, "temp_matrix_q0");
    sc_trace(mVcdFile, temp_matrix_address1, "temp_matrix_address1");
    sc_trace(mVcdFile, temp_matrix_ce1, "temp_matrix_ce1");
    sc_trace(mVcdFile, temp_matrix_q1, "temp_matrix_q1");
    sc_trace(mVcdFile, j_0_0_reg_289, "j_0_0_reg_289");
    sc_trace(mVcdFile, loop_0_0_reg_321, "loop_0_0_reg_321");
    sc_trace(mVcdFile, icmp_ln129_fu_332_p2, "icmp_ln129_fu_332_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_fu_338_p2, "i_fu_338_p2");
    sc_trace(mVcdFile, i_reg_1026, "i_reg_1026");
    sc_trace(mVcdFile, trunc_ln129_fu_344_p1, "trunc_ln129_fu_344_p1");
    sc_trace(mVcdFile, trunc_ln129_reg_1031, "trunc_ln129_reg_1031");
    sc_trace(mVcdFile, trunc_ln133_fu_348_p1, "trunc_ln133_fu_348_p1");
    sc_trace(mVcdFile, trunc_ln133_reg_1036, "trunc_ln133_reg_1036");
    sc_trace(mVcdFile, shl_ln_fu_352_p3, "shl_ln_fu_352_p3");
    sc_trace(mVcdFile, shl_ln_reg_1041, "shl_ln_reg_1041");
    sc_trace(mVcdFile, icmp_ln130_fu_360_p2, "icmp_ln130_fu_360_p2");
    sc_trace(mVcdFile, icmp_ln130_reg_1046, "icmp_ln130_reg_1046");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, zext_ln134_fu_383_p1, "zext_ln134_fu_383_p1");
    sc_trace(mVcdFile, zext_ln134_reg_1050, "zext_ln134_reg_1050");
    sc_trace(mVcdFile, zext_ln134_1_fu_415_p1, "zext_ln134_1_fu_415_p1");
    sc_trace(mVcdFile, zext_ln134_1_reg_1065, "zext_ln134_1_reg_1065");
    sc_trace(mVcdFile, add_ln130_fu_430_p2, "add_ln130_fu_430_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, prod_q0, "prod_q0");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, icmp_ln87_fu_455_p2, "icmp_ln87_fu_455_p2");
    sc_trace(mVcdFile, i_1_fu_461_p2, "i_1_fu_461_p2");
    sc_trace(mVcdFile, i_1_reg_1098, "i_1_reg_1098");
    sc_trace(mVcdFile, tmp_8_reg_1103, "tmp_8_reg_1103");
    sc_trace(mVcdFile, temp_addr_9_reg_1109, "temp_addr_9_reg_1109");
    sc_trace(mVcdFile, x_1_fu_492_p2, "x_1_fu_492_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, zext_ln68_cast_fu_704_p3, "zext_ln68_cast_fu_704_p3");
    sc_trace(mVcdFile, zext_ln68_cast_reg_1119, "zext_ln68_cast_reg_1119");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, add_ln68_fu_719_p2, "add_ln68_fu_719_p2");
    sc_trace(mVcdFile, add_ln68_reg_1124, "add_ln68_reg_1124");
    sc_trace(mVcdFile, or_ln68_fu_860_p2, "or_ln68_fu_860_p2");
    sc_trace(mVcdFile, or_ln68_reg_1130, "or_ln68_reg_1130");
    sc_trace(mVcdFile, icmp_ln68_1_fu_866_p2, "icmp_ln68_1_fu_866_p2");
    sc_trace(mVcdFile, icmp_ln68_1_reg_1135, "icmp_ln68_1_reg_1135");
    sc_trace(mVcdFile, icmp_ln139_fu_979_p2, "icmp_ln139_fu_979_p2");
    sc_trace(mVcdFile, icmp_ln139_reg_1143, "icmp_ln139_reg_1143");
    sc_trace(mVcdFile, ap_CS_fsm_pp1_stage0, "ap_CS_fsm_pp1_stage0");
    sc_trace(mVcdFile, ap_block_state11_pp1_stage0_iter0, "ap_block_state11_pp1_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state12_pp1_stage0_iter1, "ap_block_state12_pp1_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0_11001, "ap_block_pp1_stage0_11001");
    sc_trace(mVcdFile, zext_ln142_fu_989_p1, "zext_ln142_fu_989_p1");
    sc_trace(mVcdFile, zext_ln142_reg_1147, "zext_ln142_reg_1147");
    sc_trace(mVcdFile, zext_ln142_1_fu_1000_p1, "zext_ln142_1_fu_1000_p1");
    sc_trace(mVcdFile, zext_ln142_1_reg_1157, "zext_ln142_1_reg_1157");
    sc_trace(mVcdFile, add_ln139_fu_1005_p2, "add_ln139_fu_1005_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter0, "ap_enable_reg_pp1_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp1_stage0_subdone, "ap_block_pp1_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp1_exit_iter0_state11, "ap_condition_pp1_exit_iter0_state11");
    sc_trace(mVcdFile, ap_enable_reg_pp1_iter1, "ap_enable_reg_pp1_iter1");
    sc_trace(mVcdFile, prod_address0, "prod_address0");
    sc_trace(mVcdFile, prod_ce0, "prod_ce0");
    sc_trace(mVcdFile, prod_we0, "prod_we0");
    sc_trace(mVcdFile, prod_d0, "prod_d0");
    sc_trace(mVcdFile, prod_address1, "prod_address1");
    sc_trace(mVcdFile, prod_ce1, "prod_ce1");
    sc_trace(mVcdFile, prod_we1, "prod_we1");
    sc_trace(mVcdFile, prod_d1, "prod_d1");
    sc_trace(mVcdFile, prod_q1, "prod_q1");
    sc_trace(mVcdFile, temp_address0, "temp_address0");
    sc_trace(mVcdFile, temp_ce0, "temp_ce0");
    sc_trace(mVcdFile, temp_we0, "temp_we0");
    sc_trace(mVcdFile, temp_d0, "temp_d0");
    sc_trace(mVcdFile, temp_q0, "temp_q0");
    sc_trace(mVcdFile, temp_address1, "temp_address1");
    sc_trace(mVcdFile, temp_ce1, "temp_ce1");
    sc_trace(mVcdFile, temp_q1, "temp_q1");
    sc_trace(mVcdFile, bitNumber_assign_reg_277, "bitNumber_assign_reg_277");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, x_0_i_reg_300, "x_0_i_reg_300");
    sc_trace(mVcdFile, i_0_i_reg_310, "i_0_i_reg_310");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, zext_ln134_3_fu_393_p1, "zext_ln134_3_fu_393_p1");
    sc_trace(mVcdFile, zext_ln134_5_fu_425_p1, "zext_ln134_5_fu_425_p1");
    sc_trace(mVcdFile, zext_ln87_fu_450_p1, "zext_ln87_fu_450_p1");
    sc_trace(mVcdFile, zext_ln68_3_fu_487_p1, "zext_ln68_3_fu_487_p1");
    sc_trace(mVcdFile, ap_block_pp1_stage0, "ap_block_pp1_stage0");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, shl_ln68_4_fu_972_p2, "shl_ln68_4_fu_972_p2");
    sc_trace(mVcdFile, zext_ln130_fu_370_p1, "zext_ln130_fu_370_p1");
    sc_trace(mVcdFile, add_ln133_fu_374_p2, "add_ln133_fu_374_p2");
    sc_trace(mVcdFile, zext_ln134_2_fu_379_p1, "zext_ln134_2_fu_379_p1");
    sc_trace(mVcdFile, add_ln134_fu_388_p2, "add_ln134_fu_388_p2");
    sc_trace(mVcdFile, trunc_ln130_fu_366_p1, "trunc_ln130_fu_366_p1");
    sc_trace(mVcdFile, or_ln130_fu_398_p2, "or_ln130_fu_398_p2");
    sc_trace(mVcdFile, add_ln133_1_fu_404_p3, "add_ln133_1_fu_404_p3");
    sc_trace(mVcdFile, zext_ln134_4_fu_411_p1, "zext_ln134_4_fu_411_p1");
    sc_trace(mVcdFile, add_ln134_1_fu_420_p2, "add_ln134_1_fu_420_p2");
    sc_trace(mVcdFile, tmp_9_fu_477_p4, "tmp_9_fu_477_p4");
    sc_trace(mVcdFile, lshr_ln_fu_498_p4, "lshr_ln_fu_498_p4");
    sc_trace(mVcdFile, zext_ln95_fu_508_p1, "zext_ln95_fu_508_p1");
    sc_trace(mVcdFile, y_fu_538_p2, "y_fu_538_p2");
    sc_trace(mVcdFile, lshr_ln1_fu_544_p4, "lshr_ln1_fu_544_p4");
    sc_trace(mVcdFile, trunc_ln95_3_fu_528_p4, "trunc_ln95_3_fu_528_p4");
    sc_trace(mVcdFile, trunc_ln95_1_fu_524_p1, "trunc_ln95_1_fu_524_p1");
    sc_trace(mVcdFile, zext_ln96_fu_554_p1, "zext_ln96_fu_554_p1");
    sc_trace(mVcdFile, y_1_fu_582_p2, "y_1_fu_582_p2");
    sc_trace(mVcdFile, lshr_ln2_fu_588_p4, "lshr_ln2_fu_588_p4");
    sc_trace(mVcdFile, trunc_ln96_1_fu_572_p4, "trunc_ln96_1_fu_572_p4");
    sc_trace(mVcdFile, xor_ln96_fu_566_p2, "xor_ln96_fu_566_p2");
    sc_trace(mVcdFile, zext_ln97_fu_598_p1, "zext_ln97_fu_598_p1");
    sc_trace(mVcdFile, trunc_ln97_1_fu_616_p4, "trunc_ln97_1_fu_616_p4");
    sc_trace(mVcdFile, xor_ln97_fu_610_p2, "xor_ln97_fu_610_p2");
    sc_trace(mVcdFile, y_2_fu_626_p2, "y_2_fu_626_p2");
    sc_trace(mVcdFile, trunc_ln6_fu_638_p4, "trunc_ln6_fu_638_p4");
    sc_trace(mVcdFile, xor_ln97_2_fu_632_p2, "xor_ln97_2_fu_632_p2");
    sc_trace(mVcdFile, y_3_fu_656_p2, "y_3_fu_656_p2");
    sc_trace(mVcdFile, trunc_ln95_fu_512_p1, "trunc_ln95_fu_512_p1");
    sc_trace(mVcdFile, tmp_4_fu_558_p3, "tmp_4_fu_558_p3");
    sc_trace(mVcdFile, xor_ln100_fu_670_p2, "xor_ln100_fu_670_p2");
    sc_trace(mVcdFile, tmp_1_fu_516_p3, "tmp_1_fu_516_p3");
    sc_trace(mVcdFile, tmp_6_fu_648_p3, "tmp_6_fu_648_p3");
    sc_trace(mVcdFile, tmp_7_fu_662_p3, "tmp_7_fu_662_p3");
    sc_trace(mVcdFile, xor_ln100_2_fu_682_p2, "xor_ln100_2_fu_682_p2");
    sc_trace(mVcdFile, tmp_5_fu_602_p3, "tmp_5_fu_602_p3");
    sc_trace(mVcdFile, xor_ln100_3_fu_688_p2, "xor_ln100_3_fu_688_p2");
    sc_trace(mVcdFile, xor_ln100_1_fu_676_p2, "xor_ln100_1_fu_676_p2");
    sc_trace(mVcdFile, xor_ln100_4_fu_694_p2, "xor_ln100_4_fu_694_p2");
    sc_trace(mVcdFile, zext_ln68_fu_711_p1, "zext_ln68_fu_711_p1");
    sc_trace(mVcdFile, zext_ln68_2_fu_715_p1, "zext_ln68_2_fu_715_p1");
    sc_trace(mVcdFile, zext_ln68_4_fu_725_p1, "zext_ln68_4_fu_725_p1");
    sc_trace(mVcdFile, zext_ln68_5_fu_735_p1, "zext_ln68_5_fu_735_p1");
    sc_trace(mVcdFile, icmp_ln68_fu_729_p2, "icmp_ln68_fu_729_p2");
    sc_trace(mVcdFile, sub_ln68_fu_749_p2, "sub_ln68_fu_749_p2");
    sc_trace(mVcdFile, sub_ln68_1_fu_761_p2, "sub_ln68_1_fu_761_p2");
    sc_trace(mVcdFile, tmp_10_fu_739_p4, "tmp_10_fu_739_p4");
    sc_trace(mVcdFile, xor_ln68_2_fu_755_p2, "xor_ln68_2_fu_755_p2");
    sc_trace(mVcdFile, select_ln68_fu_767_p3, "select_ln68_fu_767_p3");
    sc_trace(mVcdFile, select_ln68_2_fu_783_p3, "select_ln68_2_fu_783_p3");
    sc_trace(mVcdFile, sub_ln68_2_fu_791_p2, "sub_ln68_2_fu_791_p2");
    sc_trace(mVcdFile, select_ln68_1_fu_775_p3, "select_ln68_1_fu_775_p3");
    sc_trace(mVcdFile, zext_ln68_6_fu_797_p1, "zext_ln68_6_fu_797_p1");
    sc_trace(mVcdFile, zext_ln68_7_fu_801_p1, "zext_ln68_7_fu_801_p1");
    sc_trace(mVcdFile, lshr_ln68_fu_805_p2, "lshr_ln68_fu_805_p2");
    sc_trace(mVcdFile, lshr_ln68_1_fu_811_p2, "lshr_ln68_1_fu_811_p2");
    sc_trace(mVcdFile, and_ln68_1_fu_817_p2, "and_ln68_1_fu_817_p2");
    sc_trace(mVcdFile, xor_ln68_fu_827_p2, "xor_ln68_fu_827_p2");
    sc_trace(mVcdFile, zext_ln68_1_fu_832_p1, "zext_ln68_1_fu_832_p1");
    sc_trace(mVcdFile, shl_ln68_fu_836_p2, "shl_ln68_fu_836_p2");
    sc_trace(mVcdFile, zext_ln100_fu_700_p1, "zext_ln100_fu_700_p1");
    sc_trace(mVcdFile, trunc_ln68_fu_823_p1, "trunc_ln68_fu_823_p1");
    sc_trace(mVcdFile, xor_ln68_1_fu_842_p2, "xor_ln68_1_fu_842_p2");
    sc_trace(mVcdFile, and_ln68_fu_854_p2, "and_ln68_fu_854_p2");
    sc_trace(mVcdFile, shl_ln68_1_fu_848_p2, "shl_ln68_1_fu_848_p2");
    sc_trace(mVcdFile, zext_ln68_8_fu_872_p1, "zext_ln68_8_fu_872_p1");
    sc_trace(mVcdFile, xor_ln68_3_fu_878_p2, "xor_ln68_3_fu_878_p2");
    sc_trace(mVcdFile, select_ln68_3_fu_884_p3, "select_ln68_3_fu_884_p3");
    sc_trace(mVcdFile, select_ln68_5_fu_896_p3, "select_ln68_5_fu_896_p3");
    sc_trace(mVcdFile, select_ln68_4_fu_890_p3, "select_ln68_4_fu_890_p3");
    sc_trace(mVcdFile, sub_ln68_3_fu_903_p2, "sub_ln68_3_fu_903_p2");
    sc_trace(mVcdFile, zext_ln68_9_fu_875_p1, "zext_ln68_9_fu_875_p1");
    sc_trace(mVcdFile, zext_ln68_10_fu_909_p1, "zext_ln68_10_fu_909_p1");
    sc_trace(mVcdFile, shl_ln68_2_fu_921_p2, "shl_ln68_2_fu_921_p2");
    sc_trace(mVcdFile, tmp_11_fu_927_p4, "tmp_11_fu_927_p4");
    sc_trace(mVcdFile, zext_ln68_11_fu_913_p1, "zext_ln68_11_fu_913_p1");
    sc_trace(mVcdFile, zext_ln68_12_fu_917_p1, "zext_ln68_12_fu_917_p1");
    sc_trace(mVcdFile, shl_ln68_3_fu_944_p2, "shl_ln68_3_fu_944_p2");
    sc_trace(mVcdFile, lshr_ln68_2_fu_950_p2, "lshr_ln68_2_fu_950_p2");
    sc_trace(mVcdFile, select_ln68_6_fu_937_p3, "select_ln68_6_fu_937_p3");
    sc_trace(mVcdFile, and_ln68_2_fu_956_p2, "and_ln68_2_fu_956_p2");
    sc_trace(mVcdFile, zext_ln68_13_fu_969_p1, "zext_ln68_13_fu_969_p1");
    sc_trace(mVcdFile, trunc_ln139_fu_985_p1, "trunc_ln139_fu_985_p1");
    sc_trace(mVcdFile, or_ln139_fu_994_p2, "or_ln139_fu_994_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_idle_pp1, "ap_idle_pp1");
    sc_trace(mVcdFile, ap_enable_pp1, "ap_enable_pp1");
#endif

    }
}

matrix_mul_1::~matrix_mul_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete temp_matrix_U;
    delete prod_U;
    delete temp_U;
}

void matrix_mul_1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(icmp_ln129_fu_332_p2.read(), ap_const_lv1_0))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(icmp_ln129_fu_332_p2.read(), ap_const_lv1_0))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state11.read()))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(icmp_ln129_fu_332_p2.read(), ap_const_lv1_1))) {
            ap_enable_reg_pp1_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp1_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp1_exit_iter0_state11.read()))) {
            ap_enable_reg_pp1_iter1 = (ap_condition_pp1_exit_iter0_state11.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp1_iter1 = ap_enable_reg_pp1_iter0.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(icmp_ln129_fu_332_p2.read(), ap_const_lv1_1))) {
            ap_enable_reg_pp1_iter1 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        bitNumber_assign_reg_277 = i_reg_1026.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        bitNumber_assign_reg_277 = ap_const_lv8_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i_0_i_reg_310 = i_1_reg_1098.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_0_i_reg_310 = ap_const_lv3_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln130_fu_360_p2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        j_0_0_reg_289 = add_ln130_fu_430_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln129_fu_332_p2.read(), ap_const_lv1_0))) {
        j_0_0_reg_289 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln129_fu_332_p2.read(), ap_const_lv1_1))) {
        loop_0_0_reg_321 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln139_fu_979_p2.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        loop_0_0_reg_321 = add_ln139_fu_1005_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        x_0_i_reg_300 = x_1_fu_492_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        x_0_i_reg_300 = prod_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        add_ln68_reg_1124 = add_ln68_fu_719_p2.read();
        icmp_ln68_1_reg_1135 = icmp_ln68_1_fu_866_p2.read();
        or_ln68_reg_1130 = or_ln68_fu_860_p2.read();
        zext_ln68_cast_reg_1119 = zext_ln68_cast_fu_704_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln87_fu_455_p2.read()))) {
        i_1_reg_1098 = i_1_fu_461_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_1026 = i_fu_338_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln130_reg_1046 = icmp_ln130_fu_360_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln139_reg_1143 = icmp_ln139_fu_979_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln129_fu_332_p2.read(), ap_const_lv1_0))) {
        shl_ln_reg_1041 = shl_ln_fu_352_p3.read();
        trunc_ln129_reg_1031 = trunc_ln129_fu_344_p1.read();
        trunc_ln133_reg_1036 = trunc_ln133_fu_348_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(icmp_ln87_fu_455_p2.read(), ap_const_lv1_1))) {
        temp_addr_9_reg_1109 =  (sc_lv<6>) (zext_ln68_3_fu_487_p1.read());
        tmp_8_reg_1103 = bitNumber_assign_reg_277.read().range(4, 3);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln130_fu_360_p2.read()))) {
        zext_ln134_1_reg_1065 = zext_ln134_1_fu_415_p1.read();
        zext_ln134_reg_1050 = zext_ln134_fu_383_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln139_fu_979_p2.read()))) {
        zext_ln142_1_reg_1157 = zext_ln142_1_fu_1000_p1.read();
        zext_ln142_reg_1147 = zext_ln142_fu_989_p1.read();
    }
}

void matrix_mul_1::thread_add_ln130_fu_430_p2() {
    add_ln130_fu_430_p2 = (!ap_const_lv3_2.is_01() || !j_0_0_reg_289.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_2) + sc_biguint<3>(j_0_0_reg_289.read()));
}

void matrix_mul_1::thread_add_ln133_1_fu_404_p3() {
    add_ln133_1_fu_404_p3 = esl_concat<7,2>(trunc_ln133_reg_1036.read(), or_ln130_fu_398_p2.read());
}

void matrix_mul_1::thread_add_ln133_fu_374_p2() {
    add_ln133_fu_374_p2 = (!zext_ln130_fu_370_p1.read().is_01() || !shl_ln_reg_1041.read().is_01())? sc_lv<9>(): (sc_biguint<9>(zext_ln130_fu_370_p1.read()) + sc_biguint<9>(shl_ln_reg_1041.read()));
}

void matrix_mul_1::thread_add_ln134_1_fu_420_p2() {
    add_ln134_1_fu_420_p2 = (!matrix_offset.read().is_01() || !zext_ln134_4_fu_411_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(matrix_offset.read()) + sc_biguint<14>(zext_ln134_4_fu_411_p1.read()));
}

void matrix_mul_1::thread_add_ln134_fu_388_p2() {
    add_ln134_fu_388_p2 = (!matrix_offset.read().is_01() || !zext_ln134_2_fu_379_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(matrix_offset.read()) + sc_biguint<14>(zext_ln134_2_fu_379_p1.read()));
}

void matrix_mul_1::thread_add_ln139_fu_1005_p2() {
    add_ln139_fu_1005_p2 = (!ap_const_lv3_2.is_01() || !loop_0_0_reg_321.read().is_01())? sc_lv<3>(): (sc_biguint<3>(ap_const_lv3_2) + sc_biguint<3>(loop_0_0_reg_321.read()));
}

void matrix_mul_1::thread_add_ln68_fu_719_p2() {
    add_ln68_fu_719_p2 = (!ap_const_lv6_7.is_01() || !zext_ln68_fu_711_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_7) + sc_biguint<6>(zext_ln68_fu_711_p1.read()));
}

void matrix_mul_1::thread_and_ln68_1_fu_817_p2() {
    and_ln68_1_fu_817_p2 = (lshr_ln68_fu_805_p2.read() & lshr_ln68_1_fu_811_p2.read());
}

void matrix_mul_1::thread_and_ln68_2_fu_956_p2() {
    and_ln68_2_fu_956_p2 = (shl_ln68_3_fu_944_p2.read() & lshr_ln68_2_fu_950_p2.read());
}

void matrix_mul_1::thread_and_ln68_fu_854_p2() {
    and_ln68_fu_854_p2 = (trunc_ln68_fu_823_p1.read() & xor_ln68_1_fu_842_p2.read());
}

void matrix_mul_1::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void matrix_mul_1::thread_ap_CS_fsm_pp1_stage0() {
    ap_CS_fsm_pp1_stage0 = ap_CS_fsm.read()[9];
}

void matrix_mul_1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void matrix_mul_1::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[8];
}

void matrix_mul_1::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[10];
}

void matrix_mul_1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void matrix_mul_1::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[3];
}

void matrix_mul_1::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[4];
}

void matrix_mul_1::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[5];
}

void matrix_mul_1::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[6];
}

void matrix_mul_1::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[7];
}

void matrix_mul_1::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_mul_1::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_mul_1::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_mul_1::thread_ap_block_pp1_stage0() {
    ap_block_pp1_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_mul_1::thread_ap_block_pp1_stage0_11001() {
    ap_block_pp1_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_mul_1::thread_ap_block_pp1_stage0_subdone() {
    ap_block_pp1_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_mul_1::thread_ap_block_state11_pp1_stage0_iter0() {
    ap_block_state11_pp1_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_mul_1::thread_ap_block_state12_pp1_stage0_iter1() {
    ap_block_state12_pp1_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_mul_1::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_mul_1::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void matrix_mul_1::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(icmp_ln130_fu_360_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_ap_condition_pp1_exit_iter0_state11() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln139_fu_979_p2.read())) {
        ap_condition_pp1_exit_iter0_state11 = ap_const_logic_1;
    } else {
        ap_condition_pp1_exit_iter0_state11 = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void matrix_mul_1::thread_ap_enable_pp1() {
    ap_enable_pp1 = (ap_idle_pp1.read() ^ ap_const_logic_1);
}

void matrix_mul_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_ap_idle_pp1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp1_iter1.read()))) {
        ap_idle_pp1 = ap_const_logic_1;
    } else {
        ap_idle_pp1 = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_i_1_fu_461_p2() {
    i_1_fu_461_p2 = (!i_0_i_reg_310.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_0_i_reg_310.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void matrix_mul_1::thread_i_fu_338_p2() {
    i_fu_338_p2 = (!bitNumber_assign_reg_277.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(bitNumber_assign_reg_277.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void matrix_mul_1::thread_icmp_ln129_fu_332_p2() {
    icmp_ln129_fu_332_p2 = (!bitNumber_assign_reg_277.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(bitNumber_assign_reg_277.read() == ap_const_lv8_80);
}

void matrix_mul_1::thread_icmp_ln130_fu_360_p2() {
    icmp_ln130_fu_360_p2 = (!j_0_0_reg_289.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(j_0_0_reg_289.read() == ap_const_lv3_4);
}

void matrix_mul_1::thread_icmp_ln139_fu_979_p2() {
    icmp_ln139_fu_979_p2 = (!loop_0_0_reg_321.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(loop_0_0_reg_321.read() == ap_const_lv3_4);
}

void matrix_mul_1::thread_icmp_ln68_1_fu_866_p2() {
    icmp_ln68_1_fu_866_p2 = (!zext_ln68_2_fu_715_p1.read().is_01() || !zext_ln68_4_fu_725_p1.read().is_01())? sc_lv<1>(): (sc_biguint<64>(zext_ln68_2_fu_715_p1.read()) > sc_biguint<64>(zext_ln68_4_fu_725_p1.read()));
}

void matrix_mul_1::thread_icmp_ln68_fu_729_p2() {
    icmp_ln68_fu_729_p2 = (!zext_ln68_2_fu_715_p1.read().is_01() || !zext_ln68_4_fu_725_p1.read().is_01())? sc_lv<1>(): (sc_biguint<64>(zext_ln68_2_fu_715_p1.read()) > sc_biguint<64>(zext_ln68_4_fu_725_p1.read()));
}

void matrix_mul_1::thread_icmp_ln87_fu_455_p2() {
    icmp_ln87_fu_455_p2 = (!i_0_i_reg_310.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(i_0_i_reg_310.read() == ap_const_lv3_4);
}

void matrix_mul_1::thread_lshr_ln1_fu_544_p4() {
    lshr_ln1_fu_544_p4 = y_fu_538_p2.read().range(31, 2);
}

void matrix_mul_1::thread_lshr_ln2_fu_588_p4() {
    lshr_ln2_fu_588_p4 = y_1_fu_582_p2.read().range(31, 4);
}

void matrix_mul_1::thread_lshr_ln68_1_fu_811_p2() {
    lshr_ln68_1_fu_811_p2 = (!zext_ln68_7_fu_801_p1.read().is_01())? sc_lv<32>(): ap_const_lv32_FFFFFFFF >> (unsigned short)zext_ln68_7_fu_801_p1.read().to_uint();
}

void matrix_mul_1::thread_lshr_ln68_2_fu_950_p2() {
    lshr_ln68_2_fu_950_p2 = (!zext_ln68_12_fu_917_p1.read().is_01())? sc_lv<32>(): ap_const_lv32_FFFFFFFF >> (unsigned short)zext_ln68_12_fu_917_p1.read().to_uint();
}

void matrix_mul_1::thread_lshr_ln68_fu_805_p2() {
    lshr_ln68_fu_805_p2 = (!zext_ln68_6_fu_797_p1.read().is_01())? sc_lv<32>(): select_ln68_1_fu_775_p3.read() >> (unsigned short)zext_ln68_6_fu_797_p1.read().to_uint();
}

void matrix_mul_1::thread_lshr_ln_fu_498_p4() {
    lshr_ln_fu_498_p4 = x_0_i_reg_300.read().range(31, 1);
}

void matrix_mul_1::thread_or_ln130_fu_398_p2() {
    or_ln130_fu_398_p2 = (trunc_ln130_fu_366_p1.read() | ap_const_lv2_1);
}

void matrix_mul_1::thread_or_ln139_fu_994_p2() {
    or_ln139_fu_994_p2 = (trunc_ln139_fu_985_p1.read() | ap_const_lv2_1);
}

void matrix_mul_1::thread_or_ln68_fu_860_p2() {
    or_ln68_fu_860_p2 = (and_ln68_fu_854_p2.read() | shl_ln68_1_fu_848_p2.read());
}

void matrix_mul_1::thread_output_r_address0() {
    output_r_address0 =  (sc_lv<4>) (zext_ln142_reg_1147.read());
}

void matrix_mul_1::thread_output_r_address1() {
    output_r_address1 =  (sc_lv<4>) (zext_ln142_1_reg_1157.read());
}

void matrix_mul_1::thread_output_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()))) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_output_r_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()))) {
        output_r_ce1 = ap_const_logic_1;
    } else {
        output_r_ce1 = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_output_r_d0() {
    output_r_d0 = temp_q0.read();
}

void matrix_mul_1::thread_output_r_d1() {
    output_r_d1 = temp_q1.read();
}

void matrix_mul_1::thread_output_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln139_reg_1143.read()))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_output_r_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln139_reg_1143.read()))) {
        output_r_we1 = ap_const_logic_1;
    } else {
        output_r_we1 = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_prod_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        prod_address0 =  (sc_lv<6>) (ap_const_lv64_0);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        prod_address0 =  (sc_lv<6>) (zext_ln134_reg_1050.read());
    } else {
        prod_address0 = "XXXXXX";
    }
}

void matrix_mul_1::thread_prod_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        prod_address1 =  (sc_lv<6>) (zext_ln87_fu_450_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        prod_address1 =  (sc_lv<6>) (zext_ln134_1_reg_1065.read());
    } else {
        prod_address1 = "XXXXXX";
    }
}

void matrix_mul_1::thread_prod_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        prod_ce0 = ap_const_logic_1;
    } else {
        prod_ce0 = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_prod_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
        prod_ce1 = ap_const_logic_1;
    } else {
        prod_ce1 = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_prod_d0() {
    prod_d0 = (temp_matrix_q0.read() & state_q0.read());
}

void matrix_mul_1::thread_prod_d1() {
    prod_d1 = (temp_matrix_q1.read() & state_q1.read());
}

void matrix_mul_1::thread_prod_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln130_reg_1046.read()))) {
        prod_we0 = ap_const_logic_1;
    } else {
        prod_we0 = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_prod_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln130_reg_1046.read()))) {
        prod_we1 = ap_const_logic_1;
    } else {
        prod_we1 = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_select_ln68_1_fu_775_p3() {
    select_ln68_1_fu_775_p3 = (!icmp_ln68_fu_729_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln68_fu_729_p2.read()[0].to_bool())? tmp_10_fu_739_p4.read(): temp_q0.read());
}

void matrix_mul_1::thread_select_ln68_2_fu_783_p3() {
    select_ln68_2_fu_783_p3 = (!icmp_ln68_fu_729_p2.read()[0].is_01())? sc_lv<6>(): ((icmp_ln68_fu_729_p2.read()[0].to_bool())? xor_ln68_2_fu_755_p2.read(): zext_ln68_5_fu_735_p1.read());
}

void matrix_mul_1::thread_select_ln68_3_fu_884_p3() {
    select_ln68_3_fu_884_p3 = (!icmp_ln68_1_reg_1135.read()[0].is_01())? sc_lv<6>(): ((icmp_ln68_1_reg_1135.read()[0].to_bool())? zext_ln68_8_fu_872_p1.read(): add_ln68_reg_1124.read());
}

void matrix_mul_1::thread_select_ln68_4_fu_890_p3() {
    select_ln68_4_fu_890_p3 = (!icmp_ln68_1_reg_1135.read()[0].is_01())? sc_lv<6>(): ((icmp_ln68_1_reg_1135.read()[0].to_bool())? add_ln68_reg_1124.read(): zext_ln68_8_fu_872_p1.read());
}

void matrix_mul_1::thread_select_ln68_5_fu_896_p3() {
    select_ln68_5_fu_896_p3 = (!icmp_ln68_1_reg_1135.read()[0].is_01())? sc_lv<6>(): ((icmp_ln68_1_reg_1135.read()[0].to_bool())? xor_ln68_3_fu_878_p2.read(): zext_ln68_8_fu_872_p1.read());
}

void matrix_mul_1::thread_select_ln68_6_fu_937_p3() {
    select_ln68_6_fu_937_p3 = (!icmp_ln68_1_reg_1135.read()[0].is_01())? sc_lv<32>(): ((icmp_ln68_1_reg_1135.read()[0].to_bool())? tmp_11_fu_927_p4.read(): shl_ln68_2_fu_921_p2.read());
}

void matrix_mul_1::thread_select_ln68_fu_767_p3() {
    select_ln68_fu_767_p3 = (!icmp_ln68_fu_729_p2.read()[0].is_01())? sc_lv<6>(): ((icmp_ln68_fu_729_p2.read()[0].to_bool())? sub_ln68_fu_749_p2.read(): sub_ln68_1_fu_761_p2.read());
}

void matrix_mul_1::thread_shl_ln68_1_fu_848_p2() {
    shl_ln68_1_fu_848_p2 = (!zext_ln68_1_fu_832_p1.read().is_01())? sc_lv<8>(): zext_ln100_fu_700_p1.read() << (unsigned short)zext_ln68_1_fu_832_p1.read().to_uint();
}

void matrix_mul_1::thread_shl_ln68_2_fu_921_p2() {
    shl_ln68_2_fu_921_p2 = (!zext_ln68_10_fu_909_p1.read().is_01())? sc_lv<32>(): zext_ln68_9_fu_875_p1.read() << (unsigned short)zext_ln68_10_fu_909_p1.read().to_uint();
}

void matrix_mul_1::thread_shl_ln68_3_fu_944_p2() {
    shl_ln68_3_fu_944_p2 = (!zext_ln68_11_fu_913_p1.read().is_01())? sc_lv<32>(): ap_const_lv32_FFFFFFFF << (unsigned short)zext_ln68_11_fu_913_p1.read().to_uint();
}

void matrix_mul_1::thread_shl_ln68_4_fu_972_p2() {
    shl_ln68_4_fu_972_p2 = (!zext_ln68_13_fu_969_p1.read().is_01())? sc_lv<4>(): ap_const_lv4_1 << (unsigned short)zext_ln68_13_fu_969_p1.read().to_uint();
}

void matrix_mul_1::thread_shl_ln68_fu_836_p2() {
    shl_ln68_fu_836_p2 = (!zext_ln68_1_fu_832_p1.read().is_01())? sc_lv<8>(): ap_const_lv8_1 << (unsigned short)zext_ln68_1_fu_832_p1.read().to_uint();
}

void matrix_mul_1::thread_shl_ln_fu_352_p3() {
    shl_ln_fu_352_p3 = esl_concat<7,2>(trunc_ln133_fu_348_p1.read(), ap_const_lv2_0);
}

void matrix_mul_1::thread_state_address0() {
    state_address0 =  (sc_lv<3>) (zext_ln134_fu_383_p1.read());
}

void matrix_mul_1::thread_state_address1() {
    state_address1 =  (sc_lv<3>) (zext_ln134_1_fu_415_p1.read());
}

void matrix_mul_1::thread_state_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        state_ce0 = ap_const_logic_1;
    } else {
        state_ce0 = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_state_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        state_ce1 = ap_const_logic_1;
    } else {
        state_ce1 = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_sub_ln68_1_fu_761_p2() {
    sub_ln68_1_fu_761_p2 = (!add_ln68_fu_719_p2.read().is_01() || !zext_ln68_5_fu_735_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(add_ln68_fu_719_p2.read()) - sc_biguint<6>(zext_ln68_5_fu_735_p1.read()));
}

void matrix_mul_1::thread_sub_ln68_2_fu_791_p2() {
    sub_ln68_2_fu_791_p2 = (!ap_const_lv6_1F.is_01() || !select_ln68_fu_767_p3.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_1F) - sc_biguint<6>(select_ln68_fu_767_p3.read()));
}

void matrix_mul_1::thread_sub_ln68_3_fu_903_p2() {
    sub_ln68_3_fu_903_p2 = (!ap_const_lv6_1F.is_01() || !select_ln68_3_fu_884_p3.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_1F) - sc_biguint<6>(select_ln68_3_fu_884_p3.read()));
}

void matrix_mul_1::thread_sub_ln68_fu_749_p2() {
    sub_ln68_fu_749_p2 = (!zext_ln68_5_fu_735_p1.read().is_01() || !add_ln68_fu_719_p2.read().is_01())? sc_lv<6>(): (sc_biguint<6>(zext_ln68_5_fu_735_p1.read()) - sc_biguint<6>(add_ln68_fu_719_p2.read()));
}

void matrix_mul_1::thread_temp_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0.read(), ap_const_boolean_0))) {
        temp_address0 =  (sc_lv<6>) (zext_ln142_fu_989_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        temp_address0 = temp_addr_9_reg_1109.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        temp_address0 =  (sc_lv<6>) (zext_ln68_3_fu_487_p1.read());
    } else {
        temp_address0 = "XXXXXX";
    }
}

void matrix_mul_1::thread_temp_address1() {
    temp_address1 =  (sc_lv<6>) (zext_ln142_1_fu_1000_p1.read());
}

void matrix_mul_1::thread_temp_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        temp_ce0 = ap_const_logic_1;
    } else {
        temp_ce0 = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_temp_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp1_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp1_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()))) {
        temp_ce1 = ap_const_logic_1;
    } else {
        temp_ce1 = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_temp_d0() {
    temp_d0 = (select_ln68_6_fu_937_p3.read() & and_ln68_2_fu_956_p2.read());
}

void matrix_mul_1::thread_temp_matrix_address0() {
    temp_matrix_address0 =  (sc_lv<14>) (zext_ln134_3_fu_393_p1.read());
}

void matrix_mul_1::thread_temp_matrix_address1() {
    temp_matrix_address1 =  (sc_lv<14>) (zext_ln134_5_fu_425_p1.read());
}

void matrix_mul_1::thread_temp_matrix_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        temp_matrix_ce0 = ap_const_logic_1;
    } else {
        temp_matrix_ce0 = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_temp_matrix_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        temp_matrix_ce1 = ap_const_logic_1;
    } else {
        temp_matrix_ce1 = ap_const_logic_0;
    }
}

void matrix_mul_1::thread_temp_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        temp_we0 = shl_ln68_4_fu_972_p2.read();
    } else {
        temp_we0 = ap_const_lv4_0;
    }
}

void matrix_mul_1::thread_tmp_10_fu_739_p4() {
    tmp_10_fu_739_p4 = temp_q0.read().range(0, 31);
}

void matrix_mul_1::thread_tmp_11_fu_927_p4() {
    tmp_11_fu_927_p4 = shl_ln68_2_fu_921_p2.read().range(0, 31);
}

void matrix_mul_1::thread_tmp_1_fu_516_p3() {
    tmp_1_fu_516_p3 = x_0_i_reg_300.read().range(1, 1);
}

void matrix_mul_1::thread_tmp_4_fu_558_p3() {
    tmp_4_fu_558_p3 = y_fu_538_p2.read().range(2, 2);
}

void matrix_mul_1::thread_tmp_5_fu_602_p3() {
    tmp_5_fu_602_p3 = y_1_fu_582_p2.read().range(4, 4);
}

void matrix_mul_1::thread_tmp_6_fu_648_p3() {
    tmp_6_fu_648_p3 = y_2_fu_626_p2.read().range(8, 8);
}

void matrix_mul_1::thread_tmp_7_fu_662_p3() {
    tmp_7_fu_662_p3 = y_3_fu_656_p2.read().range(16, 16);
}

void matrix_mul_1::thread_tmp_9_fu_477_p4() {
    tmp_9_fu_477_p4 = bitNumber_assign_reg_277.read().range(6, 5);
}

void matrix_mul_1::thread_trunc_ln129_fu_344_p1() {
    trunc_ln129_fu_344_p1 = bitNumber_assign_reg_277.read().range(3-1, 0);
}

void matrix_mul_1::thread_trunc_ln130_fu_366_p1() {
    trunc_ln130_fu_366_p1 = j_0_0_reg_289.read().range(2-1, 0);
}

void matrix_mul_1::thread_trunc_ln133_fu_348_p1() {
    trunc_ln133_fu_348_p1 = bitNumber_assign_reg_277.read().range(7-1, 0);
}

void matrix_mul_1::thread_trunc_ln139_fu_985_p1() {
    trunc_ln139_fu_985_p1 = loop_0_0_reg_321.read().range(2-1, 0);
}

void matrix_mul_1::thread_trunc_ln68_fu_823_p1() {
    trunc_ln68_fu_823_p1 = and_ln68_1_fu_817_p2.read().range(8-1, 0);
}

void matrix_mul_1::thread_trunc_ln6_fu_638_p4() {
    trunc_ln6_fu_638_p4 = y_2_fu_626_p2.read().range(31, 8);
}

void matrix_mul_1::thread_trunc_ln95_1_fu_524_p1() {
    trunc_ln95_1_fu_524_p1 = x_0_i_reg_300.read().range(24-1, 0);
}

void matrix_mul_1::thread_trunc_ln95_3_fu_528_p4() {
    trunc_ln95_3_fu_528_p4 = x_0_i_reg_300.read().range(24, 1);
}

void matrix_mul_1::thread_trunc_ln95_fu_512_p1() {
    trunc_ln95_fu_512_p1 = x_0_i_reg_300.read().range(1-1, 0);
}

void matrix_mul_1::thread_trunc_ln96_1_fu_572_p4() {
    trunc_ln96_1_fu_572_p4 = y_fu_538_p2.read().range(25, 2);
}

void matrix_mul_1::thread_trunc_ln97_1_fu_616_p4() {
    trunc_ln97_1_fu_616_p4 = y_1_fu_582_p2.read().range(27, 4);
}

void matrix_mul_1::thread_x_1_fu_492_p2() {
    x_1_fu_492_p2 = (prod_q1.read() ^ x_0_i_reg_300.read());
}

void matrix_mul_1::thread_xor_ln100_1_fu_676_p2() {
    xor_ln100_1_fu_676_p2 = (xor_ln100_fu_670_p2.read() ^ tmp_1_fu_516_p3.read());
}

void matrix_mul_1::thread_xor_ln100_2_fu_682_p2() {
    xor_ln100_2_fu_682_p2 = (tmp_6_fu_648_p3.read() ^ tmp_7_fu_662_p3.read());
}

void matrix_mul_1::thread_xor_ln100_3_fu_688_p2() {
    xor_ln100_3_fu_688_p2 = (xor_ln100_2_fu_682_p2.read() ^ tmp_5_fu_602_p3.read());
}

void matrix_mul_1::thread_xor_ln100_4_fu_694_p2() {
    xor_ln100_4_fu_694_p2 = (xor_ln100_3_fu_688_p2.read() ^ xor_ln100_1_fu_676_p2.read());
}

void matrix_mul_1::thread_xor_ln100_fu_670_p2() {
    xor_ln100_fu_670_p2 = (trunc_ln95_fu_512_p1.read() ^ tmp_4_fu_558_p3.read());
}

void matrix_mul_1::thread_xor_ln68_1_fu_842_p2() {
    xor_ln68_1_fu_842_p2 = (shl_ln68_fu_836_p2.read() ^ ap_const_lv8_FF);
}

void matrix_mul_1::thread_xor_ln68_2_fu_755_p2() {
    xor_ln68_2_fu_755_p2 = (zext_ln68_5_fu_735_p1.read() ^ ap_const_lv6_1F);
}

void matrix_mul_1::thread_xor_ln68_3_fu_878_p2() {
    xor_ln68_3_fu_878_p2 = (zext_ln68_8_fu_872_p1.read() ^ ap_const_lv6_1F);
}

void matrix_mul_1::thread_xor_ln68_fu_827_p2() {
    xor_ln68_fu_827_p2 = (trunc_ln129_reg_1031.read() ^ ap_const_lv3_7);
}

void matrix_mul_1::thread_xor_ln96_fu_566_p2() {
    xor_ln96_fu_566_p2 = (trunc_ln95_3_fu_528_p4.read() ^ trunc_ln95_1_fu_524_p1.read());
}

void matrix_mul_1::thread_xor_ln97_2_fu_632_p2() {
    xor_ln97_2_fu_632_p2 = (trunc_ln97_1_fu_616_p4.read() ^ xor_ln97_fu_610_p2.read());
}

void matrix_mul_1::thread_xor_ln97_fu_610_p2() {
    xor_ln97_fu_610_p2 = (trunc_ln96_1_fu_572_p4.read() ^ xor_ln96_fu_566_p2.read());
}

void matrix_mul_1::thread_y_1_fu_582_p2() {
    y_1_fu_582_p2 = (zext_ln96_fu_554_p1.read() ^ y_fu_538_p2.read());
}

void matrix_mul_1::thread_y_2_fu_626_p2() {
    y_2_fu_626_p2 = (zext_ln97_fu_598_p1.read() ^ y_1_fu_582_p2.read());
}

void matrix_mul_1::thread_y_3_fu_656_p2() {
    y_3_fu_656_p2 = (trunc_ln6_fu_638_p4.read() ^ xor_ln97_2_fu_632_p2.read());
}

void matrix_mul_1::thread_y_fu_538_p2() {
    y_fu_538_p2 = (zext_ln95_fu_508_p1.read() ^ x_0_i_reg_300.read());
}

void matrix_mul_1::thread_zext_ln100_fu_700_p1() {
    zext_ln100_fu_700_p1 = esl_zext<8,1>(xor_ln100_4_fu_694_p2.read());
}

void matrix_mul_1::thread_zext_ln130_fu_370_p1() {
    zext_ln130_fu_370_p1 = esl_zext<9,3>(j_0_0_reg_289.read());
}

void matrix_mul_1::thread_zext_ln134_1_fu_415_p1() {
    zext_ln134_1_fu_415_p1 = esl_zext<64,2>(or_ln130_fu_398_p2.read());
}

void matrix_mul_1::thread_zext_ln134_2_fu_379_p1() {
    zext_ln134_2_fu_379_p1 = esl_zext<14,9>(add_ln133_fu_374_p2.read());
}

void matrix_mul_1::thread_zext_ln134_3_fu_393_p1() {
    zext_ln134_3_fu_393_p1 = esl_zext<64,14>(add_ln134_fu_388_p2.read());
}

void matrix_mul_1::thread_zext_ln134_4_fu_411_p1() {
    zext_ln134_4_fu_411_p1 = esl_zext<14,9>(add_ln133_1_fu_404_p3.read());
}

void matrix_mul_1::thread_zext_ln134_5_fu_425_p1() {
    zext_ln134_5_fu_425_p1 = esl_zext<64,14>(add_ln134_1_fu_420_p2.read());
}

void matrix_mul_1::thread_zext_ln134_fu_383_p1() {
    zext_ln134_fu_383_p1 = esl_zext<64,3>(j_0_0_reg_289.read());
}

void matrix_mul_1::thread_zext_ln142_1_fu_1000_p1() {
    zext_ln142_1_fu_1000_p1 = esl_zext<64,2>(or_ln139_fu_994_p2.read());
}

void matrix_mul_1::thread_zext_ln142_fu_989_p1() {
    zext_ln142_fu_989_p1 = esl_zext<64,3>(loop_0_0_reg_321.read());
}

void matrix_mul_1::thread_zext_ln68_10_fu_909_p1() {
    zext_ln68_10_fu_909_p1 = esl_zext<32,6>(select_ln68_5_fu_896_p3.read());
}

void matrix_mul_1::thread_zext_ln68_11_fu_913_p1() {
    zext_ln68_11_fu_913_p1 = esl_zext<32,6>(select_ln68_4_fu_890_p3.read());
}

void matrix_mul_1::thread_zext_ln68_12_fu_917_p1() {
    zext_ln68_12_fu_917_p1 = esl_zext<32,6>(sub_ln68_3_fu_903_p2.read());
}

void matrix_mul_1::thread_zext_ln68_13_fu_969_p1() {
    zext_ln68_13_fu_969_p1 = esl_zext<4,2>(tmp_8_reg_1103.read());
}

void matrix_mul_1::thread_zext_ln68_1_fu_832_p1() {
    zext_ln68_1_fu_832_p1 = esl_zext<8,3>(xor_ln68_fu_827_p2.read());
}

void matrix_mul_1::thread_zext_ln68_2_fu_715_p1() {
    zext_ln68_2_fu_715_p1 = esl_zext<64,5>(zext_ln68_cast_fu_704_p3.read());
}

void matrix_mul_1::thread_zext_ln68_3_fu_487_p1() {
    zext_ln68_3_fu_487_p1 = esl_zext<64,2>(tmp_9_fu_477_p4.read());
}

void matrix_mul_1::thread_zext_ln68_4_fu_725_p1() {
    zext_ln68_4_fu_725_p1 = esl_zext<64,6>(add_ln68_fu_719_p2.read());
}

void matrix_mul_1::thread_zext_ln68_5_fu_735_p1() {
    zext_ln68_5_fu_735_p1 = esl_zext<6,5>(zext_ln68_cast_fu_704_p3.read());
}

void matrix_mul_1::thread_zext_ln68_6_fu_797_p1() {
    zext_ln68_6_fu_797_p1 = esl_zext<32,6>(select_ln68_2_fu_783_p3.read());
}

void matrix_mul_1::thread_zext_ln68_7_fu_801_p1() {
    zext_ln68_7_fu_801_p1 = esl_zext<32,6>(sub_ln68_2_fu_791_p2.read());
}

void matrix_mul_1::thread_zext_ln68_8_fu_872_p1() {
    zext_ln68_8_fu_872_p1 = esl_zext<6,5>(zext_ln68_cast_reg_1119.read());
}

void matrix_mul_1::thread_zext_ln68_9_fu_875_p1() {
    zext_ln68_9_fu_875_p1 = esl_zext<32,8>(or_ln68_reg_1130.read());
}

void matrix_mul_1::thread_zext_ln68_cast_fu_704_p3() {
    zext_ln68_cast_fu_704_p3 = esl_concat<2,3>(tmp_8_reg_1103.read(), ap_const_lv3_0);
}

void matrix_mul_1::thread_zext_ln68_fu_711_p1() {
    zext_ln68_fu_711_p1 = esl_zext<6,5>(zext_ln68_cast_fu_704_p3.read());
}

void matrix_mul_1::thread_zext_ln87_fu_450_p1() {
    zext_ln87_fu_450_p1 = esl_zext<64,3>(i_0_i_reg_310.read());
}

void matrix_mul_1::thread_zext_ln95_fu_508_p1() {
    zext_ln95_fu_508_p1 = esl_zext<32,31>(lshr_ln_fu_498_p4.read());
}

void matrix_mul_1::thread_zext_ln96_fu_554_p1() {
    zext_ln96_fu_554_p1 = esl_zext<32,30>(lshr_ln1_fu_544_p4.read());
}

void matrix_mul_1::thread_zext_ln97_fu_598_p1() {
    zext_ln97_fu_598_p1 = esl_zext<32,28>(lshr_ln2_fu_588_p4.read());
}

void matrix_mul_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln129_fu_332_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln130_fu_360_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln130_fu_360_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(icmp_ln87_fu_455_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 512 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln139_fu_979_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp1_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp1_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln139_fu_979_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<11>) ("XXXXXXXXXXX");
            break;
    }
}

}

