// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module matrix_mul_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0,
        output_r_address1,
        output_r_ce1,
        output_r_we1,
        output_r_d1,
        state_address0,
        state_ce0,
        state_q0,
        state_address1,
        state_ce1,
        state_q1,
        matrix_offset
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_pp0_stage0 = 11'd4;
parameter    ap_ST_fsm_state5 = 11'd8;
parameter    ap_ST_fsm_state6 = 11'd16;
parameter    ap_ST_fsm_state7 = 11'd32;
parameter    ap_ST_fsm_state8 = 11'd64;
parameter    ap_ST_fsm_state9 = 11'd128;
parameter    ap_ST_fsm_state10 = 11'd256;
parameter    ap_ST_fsm_pp1_stage0 = 11'd512;
parameter    ap_ST_fsm_state13 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [31:0] output_r_d0;
output  [3:0] output_r_address1;
output   output_r_ce1;
output   output_r_we1;
output  [31:0] output_r_d1;
output  [2:0] state_address0;
output   state_ce0;
input  [31:0] state_q0;
output  [2:0] state_address1;
output   state_ce1;
input  [31:0] state_q1;
input  [13:0] matrix_offset;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg output_r_ce0;
reg output_r_we0;
reg output_r_ce1;
reg output_r_we1;
reg state_ce0;
reg state_ce1;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [13:0] temp_matrix_address0;
reg    temp_matrix_ce0;
wire   [31:0] temp_matrix_q0;
wire   [13:0] temp_matrix_address1;
reg    temp_matrix_ce1;
wire   [31:0] temp_matrix_q1;
reg   [2:0] j_0_0_reg_289;
reg   [2:0] loop_0_0_reg_321;
wire   [0:0] icmp_ln129_fu_332_p2;
wire    ap_CS_fsm_state2;
wire   [7:0] i_fu_338_p2;
reg   [7:0] i_reg_1026;
wire   [2:0] trunc_ln129_fu_344_p1;
reg   [2:0] trunc_ln129_reg_1031;
wire   [6:0] trunc_ln133_fu_348_p1;
reg   [6:0] trunc_ln133_reg_1036;
wire   [8:0] shl_ln_fu_352_p3;
reg   [8:0] shl_ln_reg_1041;
wire   [0:0] icmp_ln130_fu_360_p2;
reg   [0:0] icmp_ln130_reg_1046;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln134_fu_383_p1;
reg   [63:0] zext_ln134_reg_1050;
wire   [63:0] zext_ln134_1_fu_415_p1;
reg   [63:0] zext_ln134_1_reg_1065;
wire   [2:0] add_ln130_fu_430_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [31:0] prod_q0;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln87_fu_455_p2;
wire   [2:0] i_1_fu_461_p2;
reg   [2:0] i_1_reg_1098;
reg   [1:0] tmp_8_reg_1103;
reg   [5:0] temp_addr_9_reg_1109;
wire   [31:0] x_1_fu_492_p2;
wire    ap_CS_fsm_state8;
wire   [4:0] zext_ln68_cast_fu_704_p3;
reg   [4:0] zext_ln68_cast_reg_1119;
wire    ap_CS_fsm_state9;
wire   [5:0] add_ln68_fu_719_p2;
reg   [5:0] add_ln68_reg_1124;
wire   [7:0] or_ln68_fu_860_p2;
reg   [7:0] or_ln68_reg_1130;
wire   [0:0] icmp_ln68_1_fu_866_p2;
reg   [0:0] icmp_ln68_1_reg_1135;
wire   [0:0] icmp_ln139_fu_979_p2;
reg   [0:0] icmp_ln139_reg_1143;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state11_pp1_stage0_iter0;
wire    ap_block_state12_pp1_stage0_iter1;
wire    ap_block_pp1_stage0_11001;
wire   [63:0] zext_ln142_fu_989_p1;
reg   [63:0] zext_ln142_reg_1147;
wire   [63:0] zext_ln142_1_fu_1000_p1;
reg   [63:0] zext_ln142_1_reg_1157;
wire   [2:0] add_ln139_fu_1005_p2;
reg    ap_enable_reg_pp1_iter0;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state11;
reg    ap_enable_reg_pp1_iter1;
reg   [5:0] prod_address0;
reg    prod_ce0;
reg    prod_we0;
wire   [31:0] prod_d0;
reg   [5:0] prod_address1;
reg    prod_ce1;
reg    prod_we1;
wire   [31:0] prod_d1;
wire   [31:0] prod_q1;
reg   [5:0] temp_address0;
reg    temp_ce0;
reg   [3:0] temp_we0;
wire   [31:0] temp_d0;
wire   [31:0] temp_q0;
wire   [5:0] temp_address1;
reg    temp_ce1;
wire   [31:0] temp_q1;
reg   [7:0] bitNumber_assign_reg_277;
wire    ap_CS_fsm_state10;
reg   [31:0] x_0_i_reg_300;
reg   [2:0] i_0_i_reg_310;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln134_3_fu_393_p1;
wire   [63:0] zext_ln134_5_fu_425_p1;
wire   [63:0] zext_ln87_fu_450_p1;
wire   [63:0] zext_ln68_3_fu_487_p1;
wire    ap_block_pp1_stage0;
wire    ap_CS_fsm_state5;
wire   [3:0] shl_ln68_4_fu_972_p2;
wire   [8:0] zext_ln130_fu_370_p1;
wire   [8:0] add_ln133_fu_374_p2;
wire   [13:0] zext_ln134_2_fu_379_p1;
wire   [13:0] add_ln134_fu_388_p2;
wire   [1:0] trunc_ln130_fu_366_p1;
wire   [1:0] or_ln130_fu_398_p2;
wire   [8:0] add_ln133_1_fu_404_p3;
wire   [13:0] zext_ln134_4_fu_411_p1;
wire   [13:0] add_ln134_1_fu_420_p2;
wire   [1:0] tmp_9_fu_477_p4;
wire   [30:0] lshr_ln_fu_498_p4;
wire   [31:0] zext_ln95_fu_508_p1;
wire   [31:0] y_fu_538_p2;
wire   [29:0] lshr_ln1_fu_544_p4;
wire   [23:0] trunc_ln95_3_fu_528_p4;
wire   [23:0] trunc_ln95_1_fu_524_p1;
wire   [31:0] zext_ln96_fu_554_p1;
wire   [31:0] y_1_fu_582_p2;
wire   [27:0] lshr_ln2_fu_588_p4;
wire   [23:0] trunc_ln96_1_fu_572_p4;
wire   [23:0] xor_ln96_fu_566_p2;
wire   [31:0] zext_ln97_fu_598_p1;
wire   [23:0] trunc_ln97_1_fu_616_p4;
wire   [23:0] xor_ln97_fu_610_p2;
wire   [31:0] y_2_fu_626_p2;
wire   [23:0] trunc_ln6_fu_638_p4;
wire   [23:0] xor_ln97_2_fu_632_p2;
wire   [23:0] y_3_fu_656_p2;
wire   [0:0] trunc_ln95_fu_512_p1;
wire   [0:0] tmp_4_fu_558_p3;
wire   [0:0] xor_ln100_fu_670_p2;
wire   [0:0] tmp_1_fu_516_p3;
wire   [0:0] tmp_6_fu_648_p3;
wire   [0:0] tmp_7_fu_662_p3;
wire   [0:0] xor_ln100_2_fu_682_p2;
wire   [0:0] tmp_5_fu_602_p3;
wire   [0:0] xor_ln100_3_fu_688_p2;
wire   [0:0] xor_ln100_1_fu_676_p2;
wire   [0:0] xor_ln100_4_fu_694_p2;
wire   [5:0] zext_ln68_fu_711_p1;
wire   [63:0] zext_ln68_2_fu_715_p1;
wire   [63:0] zext_ln68_4_fu_725_p1;
wire   [5:0] zext_ln68_5_fu_735_p1;
wire   [0:0] icmp_ln68_fu_729_p2;
wire   [5:0] sub_ln68_fu_749_p2;
wire   [5:0] sub_ln68_1_fu_761_p2;
reg   [31:0] tmp_10_fu_739_p4;
wire   [5:0] xor_ln68_2_fu_755_p2;
wire   [5:0] select_ln68_fu_767_p3;
wire   [5:0] select_ln68_2_fu_783_p3;
wire   [5:0] sub_ln68_2_fu_791_p2;
wire   [31:0] select_ln68_1_fu_775_p3;
wire   [31:0] zext_ln68_6_fu_797_p1;
wire   [31:0] zext_ln68_7_fu_801_p1;
wire   [31:0] lshr_ln68_fu_805_p2;
wire   [31:0] lshr_ln68_1_fu_811_p2;
wire   [31:0] and_ln68_1_fu_817_p2;
wire   [2:0] xor_ln68_fu_827_p2;
wire   [7:0] zext_ln68_1_fu_832_p1;
wire   [7:0] shl_ln68_fu_836_p2;
wire   [7:0] zext_ln100_fu_700_p1;
wire   [7:0] trunc_ln68_fu_823_p1;
wire   [7:0] xor_ln68_1_fu_842_p2;
wire   [7:0] and_ln68_fu_854_p2;
wire   [7:0] shl_ln68_1_fu_848_p2;
wire   [5:0] zext_ln68_8_fu_872_p1;
wire   [5:0] xor_ln68_3_fu_878_p2;
wire   [5:0] select_ln68_3_fu_884_p3;
wire   [5:0] select_ln68_5_fu_896_p3;
wire   [5:0] select_ln68_4_fu_890_p3;
wire   [5:0] sub_ln68_3_fu_903_p2;
wire   [31:0] zext_ln68_9_fu_875_p1;
wire   [31:0] zext_ln68_10_fu_909_p1;
wire   [31:0] shl_ln68_2_fu_921_p2;
reg   [31:0] tmp_11_fu_927_p4;
wire   [31:0] zext_ln68_11_fu_913_p1;
wire   [31:0] zext_ln68_12_fu_917_p1;
wire   [31:0] shl_ln68_3_fu_944_p2;
wire   [31:0] lshr_ln68_2_fu_950_p2;
wire   [31:0] select_ln68_6_fu_937_p3;
wire   [31:0] and_ln68_2_fu_956_p2;
wire   [3:0] zext_ln68_13_fu_969_p1;
wire   [1:0] trunc_ln139_fu_985_p1;
wire   [1:0] or_ln139_fu_994_p2;
wire    ap_CS_fsm_state13;
reg   [10:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
end

matrix_mul_1_tempeOg #(
    .DataWidth( 32 ),
    .AddressRange( 10752 ),
    .AddressWidth( 14 ))
temp_matrix_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_matrix_address0),
    .ce0(temp_matrix_ce0),
    .q0(temp_matrix_q0),
    .address1(temp_matrix_address1),
    .ce1(temp_matrix_ce1),
    .q1(temp_matrix_q1)
);

matrix_mul_1_prod #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
prod_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(prod_address0),
    .ce0(prod_ce0),
    .we0(prod_we0),
    .d0(prod_d0),
    .q0(prod_q0),
    .address1(prod_address1),
    .ce1(prod_ce1),
    .we1(prod_we1),
    .d1(prod_d1),
    .q1(prod_q1)
);

matrix_mul_1_temp #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
temp_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_address0),
    .ce0(temp_ce0),
    .we0(temp_we0),
    .d0(temp_d0),
    .q0(temp_q0),
    .address1(temp_address1),
    .ce1(temp_ce1),
    .q1(temp_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((icmp_ln129_fu_332_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((icmp_ln129_fu_332_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state11) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((icmp_ln129_fu_332_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state11))) begin
            ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state11);
        end else if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if (((icmp_ln129_fu_332_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        bitNumber_assign_reg_277 <= i_reg_1026;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        bitNumber_assign_reg_277 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        i_0_i_reg_310 <= i_1_reg_1098;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        i_0_i_reg_310 <= 3'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln130_fu_360_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        j_0_0_reg_289 <= add_ln130_fu_430_p2;
    end else if (((icmp_ln129_fu_332_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_0_0_reg_289 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln129_fu_332_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        loop_0_0_reg_321 <= 3'd0;
    end else if (((icmp_ln139_fu_979_p2 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        loop_0_0_reg_321 <= add_ln139_fu_1005_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        x_0_i_reg_300 <= x_1_fu_492_p2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        x_0_i_reg_300 <= prod_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln68_reg_1124[5 : 3] <= add_ln68_fu_719_p2[5 : 3];
        icmp_ln68_1_reg_1135 <= icmp_ln68_1_fu_866_p2;
        or_ln68_reg_1130 <= or_ln68_fu_860_p2;
        zext_ln68_cast_reg_1119[4 : 3] <= zext_ln68_cast_fu_704_p3[4 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln87_fu_455_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        i_1_reg_1098 <= i_1_fu_461_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_1026 <= i_fu_338_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln130_reg_1046 <= icmp_ln130_fu_360_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        icmp_ln139_reg_1143 <= icmp_ln139_fu_979_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln129_fu_332_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        shl_ln_reg_1041[8 : 2] <= shl_ln_fu_352_p3[8 : 2];
        trunc_ln129_reg_1031 <= trunc_ln129_fu_344_p1;
        trunc_ln133_reg_1036 <= trunc_ln133_fu_348_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln87_fu_455_p2 == 1'd1))) begin
        temp_addr_9_reg_1109[1 : 0] <= zext_ln68_3_fu_487_p1[1 : 0];
        tmp_8_reg_1103 <= {{bitNumber_assign_reg_277[4:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln130_fu_360_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        zext_ln134_1_reg_1065[1] <= zext_ln134_1_fu_415_p1[1];
        zext_ln134_reg_1050[2 : 0] <= zext_ln134_fu_383_p1[2 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln139_fu_979_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        zext_ln142_1_reg_1157[1] <= zext_ln142_1_fu_1000_p1[1];
        zext_ln142_reg_1147[2 : 0] <= zext_ln142_fu_989_p1[2 : 0];
    end
end

always @ (*) begin
    if ((icmp_ln130_fu_360_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln139_fu_979_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state11 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state11 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        output_r_ce1 = 1'b1;
    end else begin
        output_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln139_reg_1143 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln139_reg_1143 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        output_r_we1 = 1'b1;
    end else begin
        output_r_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        prod_address0 = 64'd0;
    end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        prod_address0 = zext_ln134_reg_1050;
    end else begin
        prod_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        prod_address1 = zext_ln87_fu_450_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        prod_address1 = zext_ln134_1_reg_1065;
    end else begin
        prod_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        prod_ce0 = 1'b1;
    end else begin
        prod_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        prod_ce1 = 1'b1;
    end else begin
        prod_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln130_reg_1046 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        prod_we0 = 1'b1;
    end else begin
        prod_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln130_reg_1046 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        prod_we1 = 1'b1;
    end else begin
        prod_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        state_ce0 = 1'b1;
    end else begin
        state_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        state_ce1 = 1'b1;
    end else begin
        state_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        temp_address0 = zext_ln142_fu_989_p1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_address0 = temp_addr_9_reg_1109;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        temp_address0 = zext_ln68_3_fu_487_p1;
    end else begin
        temp_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state7) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        temp_ce0 = 1'b1;
    end else begin
        temp_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        temp_ce1 = 1'b1;
    end else begin
        temp_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        temp_matrix_ce0 = 1'b1;
    end else begin
        temp_matrix_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        temp_matrix_ce1 = 1'b1;
    end else begin
        temp_matrix_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        temp_we0 = shl_ln68_4_fu_972_p2;
    end else begin
        temp_we0 = 4'd0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln129_fu_332_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((icmp_ln130_fu_360_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((icmp_ln130_fu_360_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (icmp_ln87_fu_455_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if (~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1) & (icmp_ln139_fu_979_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1) & (icmp_ln139_fu_979_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln130_fu_430_p2 = (3'd2 + j_0_0_reg_289);

assign add_ln133_1_fu_404_p3 = {{trunc_ln133_reg_1036}, {or_ln130_fu_398_p2}};

assign add_ln133_fu_374_p2 = (zext_ln130_fu_370_p1 + shl_ln_reg_1041);

assign add_ln134_1_fu_420_p2 = (matrix_offset + zext_ln134_4_fu_411_p1);

assign add_ln134_fu_388_p2 = (matrix_offset + zext_ln134_2_fu_379_p1);

assign add_ln139_fu_1005_p2 = (3'd2 + loop_0_0_reg_321);

assign add_ln68_fu_719_p2 = (6'd7 + zext_ln68_fu_711_p1);

assign and_ln68_1_fu_817_p2 = (lshr_ln68_fu_805_p2 & lshr_ln68_1_fu_811_p2);

assign and_ln68_2_fu_956_p2 = (shl_ln68_3_fu_944_p2 & lshr_ln68_2_fu_950_p2);

assign and_ln68_fu_854_p2 = (xor_ln68_1_fu_842_p2 & trunc_ln68_fu_823_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state11_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign i_1_fu_461_p2 = (i_0_i_reg_310 + 3'd1);

assign i_fu_338_p2 = (bitNumber_assign_reg_277 + 8'd1);

assign icmp_ln129_fu_332_p2 = ((bitNumber_assign_reg_277 == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln130_fu_360_p2 = ((j_0_0_reg_289 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln139_fu_979_p2 = ((loop_0_0_reg_321 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln68_1_fu_866_p2 = ((zext_ln68_2_fu_715_p1 > zext_ln68_4_fu_725_p1) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_729_p2 = ((zext_ln68_2_fu_715_p1 > zext_ln68_4_fu_725_p1) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_455_p2 = ((i_0_i_reg_310 == 3'd4) ? 1'b1 : 1'b0);

assign lshr_ln1_fu_544_p4 = {{y_fu_538_p2[31:2]}};

assign lshr_ln2_fu_588_p4 = {{y_1_fu_582_p2[31:4]}};

assign lshr_ln68_1_fu_811_p2 = 32'd4294967295 >> zext_ln68_7_fu_801_p1;

assign lshr_ln68_2_fu_950_p2 = 32'd4294967295 >> zext_ln68_12_fu_917_p1;

assign lshr_ln68_fu_805_p2 = select_ln68_1_fu_775_p3 >> zext_ln68_6_fu_797_p1;

assign lshr_ln_fu_498_p4 = {{x_0_i_reg_300[31:1]}};

assign or_ln130_fu_398_p2 = (trunc_ln130_fu_366_p1 | 2'd1);

assign or_ln139_fu_994_p2 = (trunc_ln139_fu_985_p1 | 2'd1);

assign or_ln68_fu_860_p2 = (shl_ln68_1_fu_848_p2 | and_ln68_fu_854_p2);

assign output_r_address0 = zext_ln142_reg_1147;

assign output_r_address1 = zext_ln142_1_reg_1157;

assign output_r_d0 = temp_q0;

assign output_r_d1 = temp_q1;

assign prod_d0 = (temp_matrix_q0 & state_q0);

assign prod_d1 = (temp_matrix_q1 & state_q1);

assign select_ln68_1_fu_775_p3 = ((icmp_ln68_fu_729_p2[0:0] === 1'b1) ? tmp_10_fu_739_p4 : temp_q0);

assign select_ln68_2_fu_783_p3 = ((icmp_ln68_fu_729_p2[0:0] === 1'b1) ? xor_ln68_2_fu_755_p2 : zext_ln68_5_fu_735_p1);

assign select_ln68_3_fu_884_p3 = ((icmp_ln68_1_reg_1135[0:0] === 1'b1) ? zext_ln68_8_fu_872_p1 : add_ln68_reg_1124);

assign select_ln68_4_fu_890_p3 = ((icmp_ln68_1_reg_1135[0:0] === 1'b1) ? add_ln68_reg_1124 : zext_ln68_8_fu_872_p1);

assign select_ln68_5_fu_896_p3 = ((icmp_ln68_1_reg_1135[0:0] === 1'b1) ? xor_ln68_3_fu_878_p2 : zext_ln68_8_fu_872_p1);

assign select_ln68_6_fu_937_p3 = ((icmp_ln68_1_reg_1135[0:0] === 1'b1) ? tmp_11_fu_927_p4 : shl_ln68_2_fu_921_p2);

assign select_ln68_fu_767_p3 = ((icmp_ln68_fu_729_p2[0:0] === 1'b1) ? sub_ln68_fu_749_p2 : sub_ln68_1_fu_761_p2);

assign shl_ln68_1_fu_848_p2 = zext_ln100_fu_700_p1 << zext_ln68_1_fu_832_p1;

assign shl_ln68_2_fu_921_p2 = zext_ln68_9_fu_875_p1 << zext_ln68_10_fu_909_p1;

assign shl_ln68_3_fu_944_p2 = 32'd4294967295 << zext_ln68_11_fu_913_p1;

assign shl_ln68_4_fu_972_p2 = 4'd1 << zext_ln68_13_fu_969_p1;

assign shl_ln68_fu_836_p2 = 8'd1 << zext_ln68_1_fu_832_p1;

assign shl_ln_fu_352_p3 = {{trunc_ln133_fu_348_p1}, {2'd0}};

assign state_address0 = zext_ln134_fu_383_p1;

assign state_address1 = zext_ln134_1_fu_415_p1;

assign sub_ln68_1_fu_761_p2 = (add_ln68_fu_719_p2 - zext_ln68_5_fu_735_p1);

assign sub_ln68_2_fu_791_p2 = (6'd31 - select_ln68_fu_767_p3);

assign sub_ln68_3_fu_903_p2 = (6'd31 - select_ln68_3_fu_884_p3);

assign sub_ln68_fu_749_p2 = (zext_ln68_5_fu_735_p1 - add_ln68_fu_719_p2);

assign temp_address1 = zext_ln142_1_fu_1000_p1;

assign temp_d0 = (select_ln68_6_fu_937_p3 & and_ln68_2_fu_956_p2);

assign temp_matrix_address0 = zext_ln134_3_fu_393_p1;

assign temp_matrix_address1 = zext_ln134_5_fu_425_p1;

integer ap_tvar_int_0;

always @ (temp_q0) begin
    for (ap_tvar_int_0 = 32 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 31 - 0) begin
            tmp_10_fu_739_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_10_fu_739_p4[ap_tvar_int_0] = temp_q0[31 - ap_tvar_int_0];
        end
    end
end

integer ap_tvar_int_1;

always @ (shl_ln68_2_fu_921_p2) begin
    for (ap_tvar_int_1 = 32 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 31 - 0) begin
            tmp_11_fu_927_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            tmp_11_fu_927_p4[ap_tvar_int_1] = shl_ln68_2_fu_921_p2[31 - ap_tvar_int_1];
        end
    end
end

assign tmp_1_fu_516_p3 = x_0_i_reg_300[32'd1];

assign tmp_4_fu_558_p3 = y_fu_538_p2[32'd2];

assign tmp_5_fu_602_p3 = y_1_fu_582_p2[32'd4];

assign tmp_6_fu_648_p3 = y_2_fu_626_p2[32'd8];

assign tmp_7_fu_662_p3 = y_3_fu_656_p2[32'd16];

assign tmp_9_fu_477_p4 = {{bitNumber_assign_reg_277[6:5]}};

assign trunc_ln129_fu_344_p1 = bitNumber_assign_reg_277[2:0];

assign trunc_ln130_fu_366_p1 = j_0_0_reg_289[1:0];

assign trunc_ln133_fu_348_p1 = bitNumber_assign_reg_277[6:0];

assign trunc_ln139_fu_985_p1 = loop_0_0_reg_321[1:0];

assign trunc_ln68_fu_823_p1 = and_ln68_1_fu_817_p2[7:0];

assign trunc_ln6_fu_638_p4 = {{y_2_fu_626_p2[31:8]}};

assign trunc_ln95_1_fu_524_p1 = x_0_i_reg_300[23:0];

assign trunc_ln95_3_fu_528_p4 = {{x_0_i_reg_300[24:1]}};

assign trunc_ln95_fu_512_p1 = x_0_i_reg_300[0:0];

assign trunc_ln96_1_fu_572_p4 = {{y_fu_538_p2[25:2]}};

assign trunc_ln97_1_fu_616_p4 = {{y_1_fu_582_p2[27:4]}};

assign x_1_fu_492_p2 = (x_0_i_reg_300 ^ prod_q1);

assign xor_ln100_1_fu_676_p2 = (xor_ln100_fu_670_p2 ^ tmp_1_fu_516_p3);

assign xor_ln100_2_fu_682_p2 = (tmp_7_fu_662_p3 ^ tmp_6_fu_648_p3);

assign xor_ln100_3_fu_688_p2 = (xor_ln100_2_fu_682_p2 ^ tmp_5_fu_602_p3);

assign xor_ln100_4_fu_694_p2 = (xor_ln100_3_fu_688_p2 ^ xor_ln100_1_fu_676_p2);

assign xor_ln100_fu_670_p2 = (trunc_ln95_fu_512_p1 ^ tmp_4_fu_558_p3);

assign xor_ln68_1_fu_842_p2 = (shl_ln68_fu_836_p2 ^ 8'd255);

assign xor_ln68_2_fu_755_p2 = (zext_ln68_5_fu_735_p1 ^ 6'd31);

assign xor_ln68_3_fu_878_p2 = (zext_ln68_8_fu_872_p1 ^ 6'd31);

assign xor_ln68_fu_827_p2 = (trunc_ln129_reg_1031 ^ 3'd7);

assign xor_ln96_fu_566_p2 = (trunc_ln95_3_fu_528_p4 ^ trunc_ln95_1_fu_524_p1);

assign xor_ln97_2_fu_632_p2 = (xor_ln97_fu_610_p2 ^ trunc_ln97_1_fu_616_p4);

assign xor_ln97_fu_610_p2 = (xor_ln96_fu_566_p2 ^ trunc_ln96_1_fu_572_p4);

assign y_1_fu_582_p2 = (zext_ln96_fu_554_p1 ^ y_fu_538_p2);

assign y_2_fu_626_p2 = (zext_ln97_fu_598_p1 ^ y_1_fu_582_p2);

assign y_3_fu_656_p2 = (xor_ln97_2_fu_632_p2 ^ trunc_ln6_fu_638_p4);

assign y_fu_538_p2 = (zext_ln95_fu_508_p1 ^ x_0_i_reg_300);

assign zext_ln100_fu_700_p1 = xor_ln100_4_fu_694_p2;

assign zext_ln130_fu_370_p1 = j_0_0_reg_289;

assign zext_ln134_1_fu_415_p1 = or_ln130_fu_398_p2;

assign zext_ln134_2_fu_379_p1 = add_ln133_fu_374_p2;

assign zext_ln134_3_fu_393_p1 = add_ln134_fu_388_p2;

assign zext_ln134_4_fu_411_p1 = add_ln133_1_fu_404_p3;

assign zext_ln134_5_fu_425_p1 = add_ln134_1_fu_420_p2;

assign zext_ln134_fu_383_p1 = j_0_0_reg_289;

assign zext_ln142_1_fu_1000_p1 = or_ln139_fu_994_p2;

assign zext_ln142_fu_989_p1 = loop_0_0_reg_321;

assign zext_ln68_10_fu_909_p1 = select_ln68_5_fu_896_p3;

assign zext_ln68_11_fu_913_p1 = select_ln68_4_fu_890_p3;

assign zext_ln68_12_fu_917_p1 = sub_ln68_3_fu_903_p2;

assign zext_ln68_13_fu_969_p1 = tmp_8_reg_1103;

assign zext_ln68_1_fu_832_p1 = xor_ln68_fu_827_p2;

assign zext_ln68_2_fu_715_p1 = zext_ln68_cast_fu_704_p3;

assign zext_ln68_3_fu_487_p1 = tmp_9_fu_477_p4;

assign zext_ln68_4_fu_725_p1 = add_ln68_fu_719_p2;

assign zext_ln68_5_fu_735_p1 = zext_ln68_cast_fu_704_p3;

assign zext_ln68_6_fu_797_p1 = select_ln68_2_fu_783_p3;

assign zext_ln68_7_fu_801_p1 = sub_ln68_2_fu_791_p2;

assign zext_ln68_8_fu_872_p1 = zext_ln68_cast_reg_1119;

assign zext_ln68_9_fu_875_p1 = or_ln68_reg_1130;

assign zext_ln68_cast_fu_704_p3 = {{tmp_8_reg_1103}, {3'd0}};

assign zext_ln68_fu_711_p1 = zext_ln68_cast_fu_704_p3;

assign zext_ln87_fu_450_p1 = i_0_i_reg_310;

assign zext_ln95_fu_508_p1 = lshr_ln_fu_498_p4;

assign zext_ln96_fu_554_p1 = lshr_ln1_fu_544_p4;

assign zext_ln97_fu_598_p1 = lshr_ln2_fu_588_p4;

always @ (posedge ap_clk) begin
    shl_ln_reg_1041[1:0] <= 2'b00;
    zext_ln134_reg_1050[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln134_1_reg_1065[0] <= 1'b1;
    zext_ln134_1_reg_1065[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    temp_addr_9_reg_1109[5:2] <= 4'b0000;
    zext_ln68_cast_reg_1119[2:0] <= 3'b000;
    add_ln68_reg_1124[2:0] <= 3'b111;
    zext_ln142_reg_1147[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
    zext_ln142_1_reg_1157[0] <= 1'b1;
    zext_ln142_1_reg_1157[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
end

endmodule //matrix_mul_1
